<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com lista de famílias que podem ter sido atendidas antes tendo este solicitante como membro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Alterar Vínculo Voluntário na Triagem ou Visita</h4></div>
          <div class="panel-body">
            <div class="col-md-12 d-flex">
              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Grupo: <?php echo $this->view->codGrupo. ' - '. $this->view->nomeGrupo ?></label>  
              </ul>

              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Subgrupo: <?php echo $this->view->codSubgrupo. ' - '. $this->view->nomeSubgrupo ?></label>  
              </ul>

              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Família: <?php echo $this->view->codFamilia. ' - '. $this->view->nomeFamilia ?></label>  
              </ul>

              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Nr. Acompanhamento: <?php echo $this->view->seqlAcomp ?></label>  
              </ul>
            </div>

            <div class="table-responsive-lg">
              <table id="tabelaVoluntarios" class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Código Voluntário</th>
                  <th scope="col">Nome Voluntário</th>
                  <th scope="col">Atuação Acompanhamento</th>
                  <th scope="col">Selecione para Excluir Vínculo</th>
                </tr>
                </thead>
                
                <tbody>
                  <?php foreach ($this->view->dadosVoluntarios as $indice => $dadosVlnt) { ?>
                    <tr>
                      <td id="cd_vlnt" class="cd_vlnt" name="cd_vlnt"><?php echo $dadosVlnt['cd_vlnt']; ?></td>

                      <td id="nm_vlnt" class="nm_vlnt" name="nm_vlnt"><?php echo $dadosVlnt['nm_vlnt']; ?></td>

                      <td id="cd_atua_vlnt_acomp" class="cd_atua_vlnt_acomp" name="cd_atua_vlnt_acomp"><?php echo $dadosVlnt['cd_atua_vlnt_acompD']; ?></td>

                      <!-- Checkbox para assinalar o voluntário -->
                      <td class="text-center"><input class="voluntarioEscolhido link-check" type="checkbox" id='<?= $dadosVlnt['cd_vlnt'] ?>' onchange="cbChange(this)"></td>
                    </tr>
                  <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">

                <?php if ($this->view->origem == 'relatorioTriagem') { ?>
                  <a class="btn btn-success" href="#" onclick="sendPost('/fAAlterarRTMenu', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', cb_familia_escolhida:'<?= $this->view->codFamilia ?>'});">Retorna
                  </a>
                <?php } else { ?>
                  <a class="btn btn-success" href="#" onclick="sendPost('/fAAlterarRVMenu', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', cb_familia_escolhida:'<?= $this->view->codFamilia ?>'});">Retorna
                  </a>
                <?php } ?>

                <a class="btn btn-danger" href="#" onclick="coletaDados()">Excluir Vinculo Voluntário</a>
              </div>
            </div>

          </div>
        </div>
       </form>

       <div class="col infoErro text-center" >
         <?php if ($this->view->erroValidacao == 1) { ?>
            <small class="form-text text-danger">Exclusão de vínculo realizada com Sucesso!</small>
            <small class="form-text text-danger"><?php echo 'Voluntário: '.$this->view->voluntario.' - '.$this->view->nomeVoluntario.'!' ?></small>
            <small class="form-text text-danger"><?php echo 'Atuação: '.$this->view->atuacao ?></small>
         <?php } ?>
       </div>

      </div>
    </section>

    <script src="sendPost.js"></script>

    <script>
      // Para obter os cd_fml marcados no Checkbox (No caso só permitiremos um) //
      function coletaDados(){
         var ids = document.getElementsByClassName('voluntarioEscolhido');
         coletaIDs(ids);         
      };  
              
      function coletaIDs(dados){
        var array_dados = dados; 
        var newArray = [];

        var newArrayCombo = [];
        var indice_atuacao = [];

        for(var x = 0; x <= array_dados.length; x++){     
            if(typeof array_dados[x] == 'object'){
              if(array_dados[x].checked){
                newArray.push(array_dados[x].id);
              }          
            }
         }   

         if(newArray.length <= 0){
            var vlnt_escolhido = '';
         }

         if (vlnt_escolhido == '') {
            swal('', 'Não há voluntário escolhido!', 'warning');
         } else {

            swal({
                title: '',
                text: 'Confirma a exclusão?',
                type: 'warning',                  //"warning", "error", "success", "info"
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#D80C1B',
                confirmButtonText: 'Sim',
                cancelButtonText: 'Não',
                closeOnClickOutside: false

              }, function(isConfirm) {
                if (isConfirm) {
                   sendPost('/fAAlterarRTVoluntarioBase', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', nm_grp:'<?= $this->view->nomeGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', nm_sbgrp:'<?= $this->view->nomeSubgrupo ?>', cb_familia_escolhida:'<?= $this->view->codFamilia ?>', nm_grp_fmlr:'<?= $this->view->nomeFamilia ?>', seql_acomp:'<?= $this->view->seqlAcomp ?>', cb_voluntario_escolhido:newArray[0], origem:'<?= $this->view->origem ?>'});
                }
            })
          }
      }

      // Para possibiliar que se selecione apenas um checkbox //
      function cbChange(obj) {
        var cbs = document.getElementsByClassName("link-check");
        for (var i = 0; i < cbs.length; i++) {
           if(cbs[i] !== obj) cbs[i].checked = false;
         }
       }

    </script>
  </body>
</html>