      <!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Opções de inclusão de triagem
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary"> 
            <div class="panel-heading"><h4>Relatório de Triagem - Alteração</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                    <label class="list-group-item list-group-item-info bg-warning">Grupo: <?php echo ' '.$this->view->dadosAcompanhamento['nm_grp'] ?></label>  
                  </ul>

                  <ul class="list-group">
                    <label class="list-group-item list-group-item-info bg-warning">Subgrupo: <?php echo ' '.$this->view->dadosAcompanhamento['nm_sbgrp'] ?></label>  
                  </ul>

                  <ul class="list-group">
                    <label class="list-group-item list-group-item-info bg-warning">Família: <?php echo ' '.$this->view->dadosAcompanhamento['nm_grp_fmlr'] ?></label>  
                  </ul>
                </div>
              </div>

              <div class="form-group">
                <div class="col-md-8 d-flex">
                  <ul class="list-group">
                      <label class="col-md-12 control-label colorLabelTituloList">Segmentos Triagem</label>  
                  </ul>
                </div>

                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento1 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Educação&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>

                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTEducacaoMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Educação&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>
                </div>

                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento2 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Religiosidade&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>

                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTReligiosidadeMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Religiosidade&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>
                </div>

                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento3 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Moradia&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>

                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTMoradiaMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Moradia&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>
                </div>

                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento4 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Saúde&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>
                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTSaudeMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Saúde&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>   
                </div>
        
                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento5 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Despesa&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>
                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTDespesaMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Despesa&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>
                </div>
        
                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento6 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Renda&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>
                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTRendaMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Renda&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>
                </div>
        
                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento7 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Capacitação Profissional&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>
                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTCapProfissionalMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Capacitação Profissional&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>
                </div>

                <div class="col-md-6">
                  <ul class="list-group">
                      <?php if ($this->view->segmento8 == 0) { ?>
                        <a class="list-group-item list-group-item-info" href="#">Aspectos Íntimos&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>
                      <?php } else { ?>
                        <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTAspectoIntMenu', {cd_grp:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cd_fml:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'<?= $this->view->dadosAcompanhamento['origem'] ?>'});">Aspectos Íntimos&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span></a>
                      <?php } ?>
                  </ul>
                </div>
              </div>

              <div class="form-group">
                <div class="col-md-8 d-flex">
                  <ul class="list-group">
                      <label class="col-md-2 control-label colorLabelTituloList">Voluntário</label>  
                  </ul>
                </div>

                <div class="col-md-6">
                  <ul class="list-group">
                    <?php if ($this->view->vnclVlntAcomp == 0) { ?>
                      <a class="list-group-item list-group-item-info" href="#">Alterar Vínculo Voluntário na Triagem&nbsp;&nbsp;&nbsp;<span class="far fa-file-excel"></span></a>
                    <?php } else { ?>
                      <a class="list-group-item list-group-item-info" href="#" onclick="sendPost('/fAAlterarRTVoluntario', {cb_grupo_escolhido:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cb_subgrupo_escolhido:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>', cb_familia_escolhida:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', origem:'relatorioTriagem'});">Alterar Vínculo Voluntário na Triagem&nbsp;&nbsp;&nbsp;<span class="far fa-edit"></span>
                      </a>
                    <?php } ?>                    
                  </ul>
                </div>
              </div>

              <div class="form-group">
                <div class="col-md-8 d-flex">
                  <ul class="list-group">
                    <a class="list-group-item active bg-success" href="#" onclick="sendPost('/fAAlterarRT', {cb_grupo_escolhido:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', cb_subgrupo_escolhido:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>'});">Retorna
                    </a>
                  </ul>
                </div>
              </div>

              <!--Dados essenciais para tratamento $_POST -->
              <div class="col-md-6">
                <?php if (isset($_POST['cd_grp'])) { ?>
                  <input id="cd_grp" name="cd_grp" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $_POST['cd_grp'] ?>" hidden>
                  <input type="hidden" name="cd_grp" value="<?= $_POST['cd_grp'] ?>"> 
                <?php } else { ?>
                  <input id="cd_grp" name="cd_grp" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->dadosAcompanhamento['cd_grp'] ?>" hidden>
                  <input type="hidden" name="cd_grp" value="<?= $this->view->dadosAcompanhamento['cd_grp'] ?>"> 
                <?php } ?>

                <?php if (isset($_POST['cd_sbgrp'])) { ?>
                  <input id="cd_sbgrp" name="cd_sbgrp" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $_POST['cd_sbgrp'] ?>" hidden>
                  <input type="hidden" name="cd_sbgrp" value="<?= $_POST['cd_sbgrp'] ?>"> 
                <?php } else { ?>
                  <input id="cd_sbgrp" name="cd_sbgrp" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>" hidden>
                  <input type="hidden" name="cd_sbgrp" value="<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>"> 
                <?php } ?>

                <?php if (isset($_POST['cd_fml'])) { ?>
                  <input id="cd_fml" name="cd_fml" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $_POST['cd_fml'] ?>" hidden>
                  <input type="hidden" name="cd_fml" value="<?= $_POST['cd_fml'] ?>"> 
                <?php } else { ?>
                  <input id="cd_fml" name="cd_fml" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->dadosAcompanhamento['cd_fml'] ?>" hidden>
                  <input type="hidden" name="cd_fml" value="<?= $this->view->dadosAcompanhamento['cd_fml'] ?>"> 
                <?php } ?>

                <?php if (isset($_POST['origem'])) { ?>
                  <input id="origem" name="origem" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $_POST['origem'] ?>" hidden>
                  <input type="hidden" name="origem" value="<?= $_POST['origem'] ?>"> 
                <?php } else { ?>
                  <input id="origem" name="origem" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->dadosAcompanhamento['origem'] ?>" hidden>
                  <input type="hidden" name="origem" value="<?= $this->view->dadosAcompanhamento['origem'] ?>"> 
                <?php } ?>
              </div>
              <!-- Término dos dados essenciais para tratamento $_POST -->
            
            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
           <small class="form-text text-danger">Erro: Voluntário sem nível de acesso apropriado!</small>
           <small class="form-text text-danger"><?php echo "Nível Requerido: ".$this->view->nivelRequerido." - Seu Nível Atual: ".$this->view->nivelLogado ?></small>
          
          <?php } else if ($this->view->erroValidacao == 2)  { ?>
             <small class="form-text text-danger">Alteração realizada com Sucesso!<?php echo ' Segmento Triagem: '.$this->view->nomeSegmento ?></small>

          <?php } else if ($this->view->erroValidacao == 9) { ?>
             <small class="form-text text-danger">Erro: <?php echo ' '.$this->view->erroException ?>Verifique!</small>

          <?php } ?>
        </div>

      </div>
    </section>

    <!-- Para Possibilitar $_POST -->
    <script src="sendPost.js"></script>
  </body>  
</html>