<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com lista de famílias que podem ter sido atendidas antes tendo este solicitante como membro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Consulta Relatórios Triagem/Visita Pendentes</h4></div>
          <div class="panel-body">
            <div class="table-responsive-lg">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Dt. Acompanhamento</th>
                  <th scope="col">Grupo</th>
                  <th scope="col">Subgrupo</th>
                  <th scope="col">Família</th>
                  <th scope="col">Situação Acompanhamento</th>
                  <th scope="col">Pendente</th>
                </tr>
                </thead>
                
                <tbody>
                    <?php foreach ($this->view->dadosPendentes as $indice => $pendente) { ?>
                      <tr>
                        <!-- Passa por $_GET o código da Família para mostrar dados na consulta -->
                        <td><?php echo $pendente['dt_acomp']; ?></td>

                        <td><?php echo $pendente['cd_grp']; ?></td>

                        <td><?php echo $pendente['cd_sbgrp']; ?></td>

                        <td><?php echo $pendente['cd_fml']; ?></td>

                        <td><?php echo $pendente['cd_est_acomp']; ?></td>
                        
                        <td><?php echo $pendente['cd_atvd_acomp']; ?></td>

                      </tr>
                    <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">
                <a href="/fAPreConsultarRTRVPendentes" class="btn btn-success" >Retorna</a>
              </div>
            </div>

          </div>
        </div>
       </form>
      </div>
    </section>
  </body>
</html>