<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/09/2019
      Objetivo:  Menu de Conclusão de Relatório de Triagem
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>                             
        <form class="form-horizontal" action="" method="post" id="FormAltera">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta Relatório de Triagem</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11>Campo Obrigatório </p>
              </div>

              <div class="form-group">
                <label class="col-md-3 control-label" for="cd_grp">Grupo</label>  
                <div class="col-lg-1">
                  <!-- Alterado o name="cb_grupo_escolhido", devido ao $_POST no retorno deste programa-->  
                  <input id="cd_grp" name="cb_grupo_escolhido" class="form-control input-md" readonly="" type="text" maxlength="6" value="<?= $this->view->dadosAcompanhamento['cd_grp'] ?>">
                </div>

                <div class="col-lg-5">
                  <input id="nm_grp" name="nm_grp" class="form-control input-md" readonly="" type="text" maxlength="100" value="<?= $this->view->dadosAcompanhamento['nm_grp'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-3 control-label" for="cd_sbgrp">Subgrupo</label>  
                <div class="col-lg-1">
                  <!-- Alterado o name="cb_subgrupo_escolhido", devido ao $_POST no retorno deste programa-->  
                  <input id="cd_sbgrp" name="cb_subgrupo_escolhido" class="form-control input-md" readonly="" type="text" maxlength="6" value="<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>">
                </div>

                <div class="col-lg-5">
                  <input id="nm_sbgrp" name="nm_sbgrp" class="form-control input-md" readonly="" type="text" maxlength="100" value="<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-3 control-label" for="cd_fml">Família</label>  
                <div class="col-lg-1">
                  <input id="cd_fml" name="cd_fml" class="form-control input-md" readonly="" type="text" maxlength="6" value="<?= $this->view->dadosAcompanhamento['cd_fml'] ?>">
                </div>

                <div class="col-lg-5">
                  <input id="nm_grp_fmlr" name="nm_grp_fmlr" class="form-control input-md" readonly="" type="text" maxlength="100" value="<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-3 control-label" for="seql_acomp">Nr. Acompanhamento</label>  
                <div class="col-lg-1">
                  <input id="seql_acomp" name="seql_acomp" class="form-control input-md" readonly="" type="text" maxlength="6" value="<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>">
                </div>
              </div>              

              <div class="form-group">
                <label class="col-md-3 control-label" for="dt_acomp">Data Triagem<h11>*</h11></label>  
                <div class="col-lg-3">
                  <input readonly="" id="dataFormularioN" name="dt_acomp" placeholder="DD/MM/AAAA" class="form-control input-md" type="text" maxlength="10"  value="<?= $this->view->dadosAcompanhamento['dt_acomp'] ?>">
                </div>
              </div>

              <div class="form-group">    
                <label class="col-md-3 control-label" for="cd_avalia_triagem">Avaliação da Triagem<h11>*</h11></label>
                <div class="col-lg-9">
                  <select autofocus="" id="cd_avalia_triagem" name="cd_avalia_triagem" class="form-control" disabled="">
                    
                    <?php function selected2( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>
                    
                    <option value="2"<?php echo selected2('2', $this->view->dadosAcompanhamento['cd_avalia_triagem']); ?>>Deverá haver nova visita de Triagem</option>
                    
                    <option value="3"<?php echo selected2('3', $this->view->dadosAcompanhamento['cd_avalia_triagem']); ?>>Família será atendida pelo Subgrupo</option>

                    <option value="4"<?php echo selected2('4', $this->view->dadosAcompanhamento['cd_avalia_triagem']); ?>>Família Não será atendida pelo Subgrupo neste momento e deverá retornar a lista de espera</option>

                    <option value="5"<?php echo selected2('5', $this->view->dadosAcompanhamento['cd_avalia_triagem']); ?>>Família Não será atendida pelo Subgrupo neste momento por mudança de endereço e impossiblidade de triagem</option>

                    <option value="6"<?php echo selected2('6', $this->view->dadosAcompanhamento['cd_avalia_triagem']); ?>>Família não necessita de Atendimento</option>

                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-3 control-label" for="dsc_mtv_cd_avalia_triagem">Motivo da Avaliação da Triagem<h11>*</h11></label>
                <div class="col-lg-9">
                  <textarea id="1" name="dsc_mtv_cd_avalia_triagem" readonly="" placeholder="Por que do código de avaliação acima" class="form-control input-md" type="text" rows="4" cols="30" maxlength="500" onclick="this.style.borderColor=''"><?= $this->view->dadosAcompanhamento['dsc_mtv_cd_avalia_triagem'] ?></textarea>
                </div>
              </div>

            <!-- NR
              <div class="form-group">
                <label class="col-md-3 control-label" for="cd_fml_subs_triagem">Família Substituída<h11>*</h11></label>  
                <div class="col-lg-3">
                  <input readonly="" id="cd_fml_subs_triagem" name="cd_fml_subs_triagem" class="form-control input-md" type="text" maxlength="10"  value="<?= $this->view->dadosAcompanhamento['cd_fml_subs_triagem'] ?>">
                </div>
              </div>
            -->

              <div class="form-group">    
                <label class="col-lg-3 control-label" for="cd_crit_engjto">Critério de Engajamento Família<h11>*</h11></label>
                <div class="col-lg-7">
                  <select id="cd_crit_engjto" name="cd_crit_engjto" class="form-control" disabled="">
                    
                    <?php function selected1( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <option value="1"<?php echo selected1('1', $this->view->dadosAcompanhamento['cd_crit_engjto']); ?>>A Definir</option>
                    
                    <option value="2"<?php echo selected1('2', $this->view->dadosAcompanhamento['cd_crit_engjto']); ?>>Vulnerabilidade por motivo de doença, idade avançada ou deficiência física-mental</option>

                    <option value="3"<?php echo selected1('3', $this->view->dadosAcompanhamento['cd_crit_engjto']); ?>>Gestante desempregada e sem suporte familiar</option>
                   
                    <option value="4"<?php echo selected1('4', $this->view->dadosAcompanhamento['cd_crit_engjto']); ?>>Família com renda insuficiente e que não se enquadre nas situações anteriores</option>
                   
                    <option value="5"<?php echo selected1('5', $this->view->dadosAcompanhamento['cd_crit_engjto']); ?>>É atendida por outra instituição</option>
                   
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-3 control-label" for="dsc_consid_finais_triagem">Considerações Finais da Triagem<h11>*</h11></label>
                <div class="col-lg-9">
                  <textarea id="2" name="dsc_consid_finais_triagem" readonly="" placeholder="Descreva as Considerações finais" class="form-control input-md" type="text" rows="4" cols="30" maxlength="500" onclick="this.style.borderColor=''"><?= $this->view->dadosAcompanhamento['dsc_consid_finais_triagem'] ?></textarea>
                </div>
              </div>
              
              <div class="form-group" pading="1px">
                <div class="col-lg-12">
                  <fieldset class="text-center">                             
                    <legend class="info_voluntario">Segmentos</legend>

                    <?php if ($this->view->segmento1 == 0) { ?>
                      <a href="#" class="btn btn-info">Educação&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTEducacaoMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Educação&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->segmento2 == 0) { ?>
                      <a href="#" class="btn btn-info">Religiosidade&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTReligiosidadeMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Religiosidade&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->segmento3 == 0) { ?>
                      <a href="#" class="btn btn-info">Moradia&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTMoradiaMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Moradia&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->segmento4 == 0) { ?>
                      <a href="#" class="btn btn-info">Saúde&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>                  
                      <a href="#" onclick="sendPost('/fAConsultarRTSaudeMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Saúde&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->segmento5 == 0) { ?>
                      <a href="#" class="btn btn-info">Despesa&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTDespesaMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Despesa&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->segmento6 == 0) { ?>
                      <a href="#" class="btn btn-info">Renda&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTRendaMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Renda&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->segmento7 == 0) { ?>
                      <a href="#" class="btn btn-info">Capacitação Profissional&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTCapProfissionalMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Capacitação Profissional&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->segmento8 == 0) { ?>
                      <a href="#" class="btn btn-info">Asp. Íntimos&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTAspectoIntMenu', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>'});" class="btn btn-info">Asp. Íntimos&nbsp;<span class="fas fa-check" style="color:blue"></span>
                      </a>
                    <?php } ?>

                    <?php if ($this->view->vnclVlntAcomp == 0) { ?>
                      <a href="#" class="btn btn-info">Voluntários&nbsp;<span class="fas fa-times" style="color:brown"></span>
                      </a>                    
                    <?php } else { ?>
                      <a href="#" onclick="sendPost('/fAConsultarRTVoluntario', {cd_grp:'<?= $_POST['cb_grupo_escolhido'] ?>', nm_grp:'<?= $this->view->dadosAcompanhamento['nm_grp'] ?>', cd_sbgrp:'<?= $_POST['cb_subgrupo_escolhido'] ?>', nm_sbgrp:'<?= $this->view->dadosAcompanhamento['nm_sbgrp'] ?>',cd_fml:'<?= $_POST['cb_familia_escolhida'] ?>', nm_grp_fmlr:'<?= $this->view->dadosAcompanhamento['nm_grp_fmlr'] ?>', seql_acomp:'<?= $this->view->dadosAcompanhamento['seql_acomp'] ?>', origem:'consultaRelatorios'});" class="btn btn-info">Voluntários&nbsp;<span class="fas fa-check" style="color:blue"></span>
                    </a>
                    <?php } ?>                    
                  </fieldset>                             
                </div>
              </div>

              <div class="form-group text-center">
                <label class="col-md-2 control-label" for="btnAlterar"></label>
                <div class="col-md-8">
                  <a href="#" onclick="sendPost('/fAConsultarRTRVMenu', {cb_grupo_escolhido:'<?= $this->view->dadosAcompanhamento['cd_grp'] ?>', cb_subgrupo_escolhido:'<?= $this->view->dadosAcompanhamento['cd_sbgrp'] ?>', cb_familia_escolhida:'<?= $this->view->dadosAcompanhamento['cd_fml'] ?>'});" class="btn btn-success">Retorna</a>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>
      </div>
    </section>

    <!-- Para formatar campos de entrada no formulário- não pode ficar em "layout.pthml" pois não executava -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script>
      // Script pego em "http://blog.conradosaud.com.br/artigo/26" para formatação de valores - link está em "layout.phtml" 
      $('.dinheiro').mask('#.##0,00', {reverse: true});
    </script>  

    <!-- Para Possibilitar $_POST -->
    <script src="sendPost.js"></script>
  </body>
</html>