<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com lista de famílias que podem ter sido atendidas antes tendo este solicitante como membro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Consulta Relatórios Triagem/Visitas</h4></div>
          <div class="panel-body">
            <div class="col-md-12 d-flex">
              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Grupo: <?php echo $this->view->codGrupo. ' - '. $this->view->nomeGrupo ?></label>  
              </ul>

              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Subgrupo: <?php echo $this->view->codSubgrupo. ' - '. $this->view->nomeSubgrupo ?></label>  
              </ul>

              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Família: <?php echo $this->view->codFamilia. ' - '. $this->view->nomeFamilia ?></label>  
              </ul>
            </div>

            <div class="table-responsive-lg">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Seql. Acompanhamento</th>
                  <th scope="col">Data Acompanhamento</th>
                  <th scope="col">Tipo Acompanhamento</th>
                  <th scope="col">Situação Acompanhamento</th>
                  <th scope="col">Selecione para detalhar Acompanhamento</th>
                </tr>
                </thead>
                
                <tbody>
                    <?php foreach ($this->view->acompanhamento as $indice => $acompanhamento) { ?>
                      <tr>
                        <!-- Passa por $_GET o código da Família para mostrar dados na consulta -->
                        <td><?php echo $acompanhamento['seql_acomp']; ?></td>

                        <td><?php echo $acompanhamento['dt_acomp']; ?></td>

                        <td><?php echo $acompanhamento['cd_atvd_acomp']; ?></td>

                        <td><?php echo $acompanhamento['cd_est_acomp']; ?></td>

                        <!-- Checkbox para assinalar a Família a ter relatório preenchido -->
                        <td class="text-center"><input class="seqlEscolhido link-check" type="checkbox" id='<?= $acompanhamento['seql_atvd'] ?>' value="01" onchange="cbChange(this)"></td>
                      </tr>
                    <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">
                <a href="#" onclick="sendPost('/fAConsultarRTRV', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', cb_familia_escolhida:'<?= $this->view->codFamilia ?>'});" class="btn btn-success">Retorna</a>
                <a class="btn btn-danger" href="#" onclick="coletaDados()">Consultar Relatórios</a>
              </div>
            </div>

          </div>
        </div>
       </form>
      </div>
    </section>

    <script src="sendPost.js"></script>

    <script>
      // Para obter os cd_fml marcados no Checkbox (No caso só permitiremos um) //
      function coletaDados(){
         var ids = document.getElementsByClassName('seqlEscolhido');
         coletaIDs(ids);         
      };  
              
      function coletaIDs(dados){
         var array_dados = dados; 
         var newArray = [];
         for(var x = 0; x <= array_dados.length; x++){     
              if(typeof array_dados[x] == 'object'){
                if(array_dados[x].checked){
                   newArray.push(array_dados[x].id)          
                }          
              }
         }   

         if(newArray.length <= 0 || newArray == ''){
            var seql_escolhido = '';
         }else{
            var seql_escolhido = newArray[0];
         }

         if (seql_escolhido == '') {
            swal('', 'Não há Acompanhamento escolhido!', 'warning');
         
         } else {
         
          // seql_escolhido contem ==> seql_acomp;cd_atvd_acomp
          var separa_dados = seql_escolhido.split(";");
          
          // Pega a atividade => 1-Triagem, 2-Visita
          if (separa_dados[1] == 1) {
           sendPost('/fAConsultarRTMenu', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>',cb_familia_escolhida:'<?= $this->view->codFamilia ?>', seql_acomp:separa_dados[0]});
          } else {
           sendPost('/fAConsultarRVMenu', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>',cb_familia_escolhida:'<?= $this->view->codFamilia ?>', seql_acomp:separa_dados[0], origem:'consultaRelatorios'});
          }
         }
      };

      // Para possibiliar que se selecione apenas um checkbox //
      function cbChange(obj) {
        var cbs = document.getElementsByClassName("link-check");
        for (var i = 0; i < cbs.length; i++) {
           if(cbs[i] !== obj) cbs[i].checked = false;
         }
      }
    </script>
  </body>
</html>