<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com lista de famílias que podem ter sido atendidas antes tendo este solicitante como membro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Consulta Ranking Familias aguardando Triagem</h4></div>
          <div class="panel-body">
            <div class="col-md-12 d-flex">
              <ul class="list-group">
                <label>* Pontos</label>  
              </ul>
            </div>

            <div class="table-responsive-lg">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Dt. Cadastro</th>
                  <th scope="col">Família</th>                  
                  <th scope="col">Grupo</th>
                  <th scope="col">Subgrupo</th>
                  <th scope="col">Atend. Anteriores*</th>
                  <th scope="col">Tempo de espera*</th>
                  <th scope="col">Renda Per capita*</th>
                  <th scope="col">Atend. Assistido Principal*</th>
                  <th scope="col">Total Pontos</th>
                  <th scope="col">Posição Subgrupo</th>
                </tr>
                </thead>
                
                <tbody>
                    <?php foreach ($this->view->dadosRanking as $indice => $ranking) { ?>
                      <tr>
                        <!-- Passa por $_GET o código da Família para mostrar dados na consulta -->
                        <td><?php echo $ranking['dt_cadastro_fml']; ?></td>

                        <td><?php echo $ranking['cd_fml']; ?></td>

                        <td><?php echo $ranking['cd_grp']; ?></td>

                        <td><?php echo $ranking['cd_sbgrp']; ?></td>

                        <td><?php echo $ranking['nrAssistencia']; ?></td>
                        
                        <td><?php echo $ranking['tempoRegistro']; ?></td>

                        <td><?php echo $ranking['rendaPerCapita']; ?></td>

                        <td><?php echo $ranking['reatendimento']; ?></td>

                        <td><?php echo $ranking['totalPontos']; ?></td>

                        <td><?php echo $ranking['posicaoRanking']; ?></td>

                      </tr>
                    <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">
                <a href="/fAPreConsultarRankingFml" class="btn btn-success" >Retorna</a>
              </div>
            </div>

          </div>
        </div>
       </form>
      </div>
    </section>
  </body>
</html>