<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu Inicial de opções de Acompanhamento de Famílias
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
           <small class="form-text text-danger">Erro: Voluntário sem nível de acesso apropriado!</small>
           <small class="form-text text-danger"><?php echo "Nível Requerido: ".$this->view->nivelRequerido." - Seu Nível Atual: ".$this->view->nivelLogado ?></small>

          <?php } else if ($this->view->erroValidacao == 9) { ?>
             <small class="form-text text-danger">Erro: <?php echo ' '.$this->view->erroException ?>Verifique!</small>

          <?php } ?>
        </div>

        <fieldset>    
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary"> 
            <div class="panel-heading"><h4>Acompanhamento de Família</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <label class="col-md-12 control-label colorLabelTituloList">Triagem</label>  
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaAcompanhamentoPreIncluirRelTriagem">Incluir Relatório - Segmentos Triagem</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreAlterarRT">Alterar Relatório - Segmentos Triagem</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreConcluirRT">Concluir Relatório Triagem</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreRevisarRT">Revisar e Formalizar Relatório Triagem</a>
                  </ul>
                </div>
              </div>
        
              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <label class="col-md-12 control-label colorLabelTituloList">Visita</label>  
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreIncluirRV">Incluir Relatório Visita</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreAlterarRV">Alterar Relatório Visita</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreConcluirRV">Concluir Relatório Visita</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreRevisarRV">Revisar e Formalizar Relatório Visita</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreIncluirRD">Formalizar Relatório Desligamento</a>
                  </ul>
                </div>
              </div>

              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <label class="col-md-12 control-label colorLabelTituloList">Consultas</label>  
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreConsultarRTRV">Relatório Triagem/Visita Revisado/Andamento</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreConsultarRTRVPendentes">Relatório Triagem/Visita Pendente<span class="badge badge-warning"><?= $this->view->qtdPendenciasRelatorios ?></span></a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/fAPreConsultarRankingFml">Ranking Famílias aguardando Triagem</a>
                  </ul>
                </div>

                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <a class="list-group-item active bg-success" href="/menuPrincipal">Retorna</a>
                  </ul>
                </div>
              </div>
      
            </div>
          </div>
        </form>
        </fieldset>

      <!-- Passou para cima
        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
           <small class="form-text text-danger">Erro: Voluntário sem nível de acesso apropriado!</small>
           <small class="form-text text-danger"><?php echo "Nível Requerido: ".$this->view->nivelRequerido." - Seu Nível Atual: ".$this->view->nivelLogado ?></small>



          <?php } else if ($this->view->erroValidacao == 9) { ?>
             <small class="form-text text-danger">Erro: <?php echo ' '.$this->view->erroException ?>Verifique!</small>

          <?php } ?>
        </div>
      -->

      </div>
    </section>
  </body>

</html>