<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 24/10/2019
      Objetivo:  Menu Inicial de opções de Recursos Financeiros
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary"> 
            <div class="panel-heading"><h4>Recurso Financeiro de Família</h4></div>
            <div class="panel-body">
              
              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <label class="col-md-12 control-label colorLabelTituloList">Solicitação de Recurso Financeiro</label>  
                  </ul>
                </div>

                <div class="col-md-3">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/recFinanFamiliaPreSolicitar">Gerenciamento da Solicitação</a>
                  </ul>
                </div>
            
                <div class="col-md-3">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/recFinanFamiliaPreConsultar">Consulta Solicitação</a>
                  </ul>
                </div>

                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <a class="list-group-item active bg-success" href="/menuPrincipal">Retorna</a>
                  </ul>
                </div>
              </div>
      
            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
           <small class="form-text text-danger">Erro: Voluntário sem nível de acesso apropriado!</small>
           <small class="form-text text-danger"><?php echo "Nível Requerido: ".$this->view->nivelRequerido." - Seu Nível Atual: ".$this->view->nivelLogado ?></small>
          
          <?php } else if ($this->view->erroValidacao == 3) { ?>
           <small class="form-text text-danger">Não há famílias cadastradas a serem rankeadas!</small>

          <?php } else if ($this->view->erroValidacao == 9) { ?>
             <small class="form-text text-danger">Erro: <?php echo ' '.$this->view->erroException ?>Verifique!</small>

          <?php } ?>
        </div>

      </div>
    </section>
  </body>

</html>