<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com lista de famílias que podem ter sido atendidas antes tendo este solicitante como membro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Recurso Financeiro - Consulta Solicitações</h4></div>
          <div class="panel-body">

            <div class="col-md-12 control-label text-center">
              <?php if ($this->view->erroValidacao == 2) { ?>
                <small class="form-text" style="background-color: #69C8E0; color: white; font-size: 100%">Cancelamento da Solicitação Realizado com Sucesso!</small>

                <p class="form-text text-danger">&nbsp</p>

              <?php } else if ($this->view->erroValidacao == 3) { ?>
                <small class="form-text" style="background-color: #69C8E0; color: white; font-size: 100%">Remessa para Autorização realizada com Sucesso!</small>

                <p class="form-text text-danger">&nbsp</p>
                
              <?php } else if ($this->view->erroValidacao == 0) { ?>
                <p class="form-text text-danger">&nbsp</p>

              <?php } ?>
            </div>


            <div class="col-md-12 d-flex">
              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Grupo: <?php echo $this->view->codGrupo. ' - '. $this->view->nomeGrupo ?></label>  
              </ul>

              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Subgrupo: <?php echo $this->view->codSubgrupo. ' - '. $this->view->nomeSubgrupo ?></label>  
              </ul>
            </div>


            <div class="table-responsive-lg">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Seql Pedido</th>
                  <th scope="col">Data Pedido</th>
                  <th scope="col">Descrição Resumida</th>
                  <th scope="col">Menor Valor Encontrado (R$)</th>
                  <th scope="col">Arquivo Orçamento</th>
                  <th scope="col">VMR</th>
                  <th scope="col">Situação</th>
                  <th scope="col">Responsável Solicitante</th>
                  <th scope="col">Selecione p/Detalhar Solicitação</th>
                </tr>
                </thead>
                
                <tbody>
                    <?php foreach ($this->view->pedidoRecFinan as $indice => $pedido) { ?>
                      <tr>
                        <!-- Passa por $_GET o código da Família para mostrar dados na consulta -->
                        <td><?php echo $pedido['seql_pedido_finan']; ?></td>

                        <td><?php echo $pedido['dt_incl_pedido_format']; ?></td>

                        <!-- Para definir largura fixa da coluna -->
                        <td class="larguraColunaPedidoResumido"><?php echo $pedido['dsc_resum_pedido']; ?></td>

                        <td><?php echo $pedido['menor_vlr_encontra']; ?></td>
                        
                        <td><?php echo $pedido['arq_orc_pedido']; ?></td>

                        <td><?php echo $pedido['nm_tip_enquadra_format']; ?></td>

                        <td><?php echo $pedido['nm_est_pedido_format']; ?></td>

                        <td><?php echo $pedido['nm_vlnt_resp_pedido']; ?></td>

                        <!-- Checkbox para assinalar o pedido a ser gerenciado -->
                        <td class="text-center"><input class="pedidoEscolhido link-check" type="checkbox" id='<?= $pedido['pedidoRF'] ?>' value="01" onchange="cbChange(this)"></td>
                      </tr>
                    <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">
                <a href="/recFinanFamiliaPreConsultar" class="btn btn-success" >Retorna</a>
                
                <a class="btn btn-primary" href="#" onclick="coletaDados()">Detalhar Solicitação</a>
              </div>
            </div>

          </div>
        </div>
       </form>
      </div>
    </section>

    <script src="sendPost.js"></script>

    <script>
      // Para obter os cd_fml marcados no Checkbox (No caso só permitiremos um) //
      function coletaDados(){
         var ids = document.getElementsByClassName('pedidoEscolhido');
         coletaIDs(ids);         
      };  
              
      function coletaIDs(dados){
         var array_dados = dados; 
         var newArray = [];
         for(var x = 0; x <= array_dados.length; x++){     
              if(typeof array_dados[x] == 'object'){
                if(array_dados[x].checked){
                   newArray.push(array_dados[x].id)          
                }          
              }
         }   

         if(newArray.length <= 0 || newArray == ''){
            var pedido_escolhido = '';
         
         } else {
            // Como foi pego pedidoRF, está "cd_grp;cd_sbgrp;seq_pedido" 
            var pedido_escolhido_c = newArray[0];
            pedido_escolhido_c     = pedido_escolhido_c.split(';');
            var grupo_escolhido    = pedido_escolhido_c[0];
            var subgrupo_escolhido = pedido_escolhido_c[1];
            var seql_escolhido     = pedido_escolhido_c[2];
         }

         if (pedido_escolhido == '') {
            swal('', 'Não há Solicitação de Pedido escolhida!', 'warning');
         
         } else {
           sendPost('/recFinanFamiliaSolicitarMenu', {cb_grupo_escolhido:grupo_escolhido, cb_subgrupo_escolhido:subgrupo_escolhido, seql_pedido_escolhido:seql_escolhido, nome_grupo:'<?= $this->view->nomeGrupo ?>', nome_subgrupo:'<?= $this->view->nomeSubgrupo ?>', origem:'gerenciamento'});
         }
      };

      // Para possibiliar que se selecione apenas um checkbox //
      function cbChange(obj) {
        var cbs = document.getElementsByClassName("link-check");
        for (var i = 0; i < cbs.length; i++) {
           if(cbs[i] !== obj) cbs[i].checked = false;
         }
      }

      function chamaInsereDados(){
         sendPost('/recFinanFamiliaSolicitarMenu', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', nome_grupo:'<?= $this->view->nomeGrupo ?>', nome_subgrupo:'<?= $this->view->nomeSubgrupo ?>', origem:"inclusao"});         
      };  

    </script>
  </body>
</html>