<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 02/11/2019
      Objetivo:  Menu com lista de famílias que podem ser incluídas na solicitação de pedido financeiro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Família Beneficiada em Solicitação Pedido Financeiro</h4></div>
          <div class="panel-body">
            <div class="col-md-12 d-flex">
              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Grupo: <?php echo $this->view->codGrupo. ' - '. $this->view->nomeGrupo ?></label>  
              </ul>

              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Subgrupo: <?php echo $this->view->codSubgrupo. ' - '. $this->view->nomeSubgrupo ?></label>  
              </ul>
              
              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Seq. Solicitação: <?php echo $this->view->seqlPedidoFinan ?></label>  
              </ul>
            </div>

            <div class="table-responsive-lg">
              <table id="tabelaVoluntarios" class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Código Família</th>
                  <th scope="col">Nome Família</th>
                  <th scope="col">Família Beneficiada com esta Solicitação</th>
                  <th scope="col">Selecione para Incluir ou Cancelar</th>
                </tr>
                </thead>
                
                <tbody>
                  <?php foreach ($this->view->dadosFamilias as $indice => $dadosFml) { ?>
                    <?php if ($dadosFml['vinculado'] == 'Não') { ?>
                      <tr style="color: red">
                    <?php } else { ?>
                      <tr style="color: blue">
                    <?php } ?>                      

                      <td id="cd_fml" class="cd_fml" name="cd_fml"><?php echo $dadosFml['cd_fml']; ?></td>

                      <td id="nm_grp_fmlr" class="nm_grp_fmlr" name="nm_grp_fmlr"><?php echo $dadosFml['nm_grp_fmlr']; ?></td>

                      <td id="vinculado" class="vinculado" name="vinculado"><?php echo $dadosFml['vinculado']; ?></td>

                      <!-- Checkbox para assinalar a família -->
                      <td class="text-center"><input class="familiaEscolhida link-check" type="checkbox" id='<?= $dadosFml['cd_fml_sn'] ?>'></td>
                    </tr>
                  <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">


                <!-- RETORNOS -->


                <?php if ($this->view->origem == 'gerenciamento') { ?>
                  <a class="btn btn-success" href="#" onclick="sendPost('/recFinanFamiliaSolicitarMenu', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', nome_grupo:'<?= $this->view->nomeGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', nome_subgrupo:'<?= $this->view->nomeSubgrupo ?>', seql_pedido_finan:'<?= $this->view->seqlPedidoFinan ?>', origem:'<?= $this->view->origem ?>'});">Retorna
                  </a>

                <!--?php } else { ?>-->
                <?php } ?>

                <a class="btn btn-primary" href="#" onclick="coletaDadosI()">Inclui Participação de Família</a>
                
                <a class="btn btn-danger" href="#" onclick="coletaDadosE()">Cancela Participação de Família</a>

              </div>
            </div>
          </div>
        </div>
       </form>

       <div class="col infoErro text-center" >
         <?php if ($this->view->erroValidacao == 1) { ?>
            <small class="form-text text-danger">Inclusão realizada com Sucesso!</small>

         <?php } else if ($this->view->erroValidacao == 2) { ?>
            <small class="form-text text-danger">Não há Famílias na condição em Grupo/Subgrupo!</small>

         <?php } else if ($this->view->erroValidacao == 3) { ?>
            <small class="form-text text-danger">Cancelamento realizado com Sucesso!</small>
         <?php } ?>
       </div>

      </div>
    </section>

    <script src="sendPost.js"></script>

    <script>
      function coletaDadosE(){
         var ids = document.getElementsByClassName('familiaEscolhida');
         coletaIDsE(ids);         
      };  
              
      function coletaIDsE(dados){
        var array_dados = dados; 
        var newArray = [];

        for(var x = 0; x <= array_dados.length; x++){     
            if(typeof array_dados[x] == 'object'){
              if(array_dados[x].checked){
                newArray.push(array_dados[x].id);
              }          
            }
         }   

         if(newArray.length <= 0  || newArray == ''){
            var fml_escolhida = '';
         } 

         if (fml_escolhida == '') {
            swal('', 'Não há família escolhida!', 'warning');

         } else {

            var remetePost = 1;

            for (var p = 0; p < newArray.length; p++) {
              var fml_sn_escolhida = newArray[p];
              fml_sn_escolhida = fml_sn_escolhida.split(';');
              var fml_escolhida = fml_sn_escolhida[0]
              var sn_escolhido = fml_sn_escolhida[1]

              if (sn_escolhido == 'n') {
                remetePost = 0;
                break;
              }
            }

            if (remetePost == 1) {
              swal({
                  title: '',
                  text: 'Confirma o cancelamento da família na Solicitação?',
                  type: 'warning',                  //"warning", "error", "success", "info"
                  showCancelButton: true,
                  confirmButtonColor: '#3085d6',
                  cancelButtonColor: '#D80C1B',
                  confirmButtonText: 'Sim',
                  cancelButtonText: 'Não',
                  closeOnClickOutside: false

                }, function(isConfirm) {
                  if (isConfirm) {
                     sendPost('/recFinanFamiliaVincularBase', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', nome_grupo:'<?= $this->view->nomeGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', nome_subgrupo:'<?= $this->view->nomeSubgrupo ?>', seql_pedido_finan:'<?= $this->view->seqlPedidoFinan ?>', familia_escolhida:newArray, origem:'<?= $this->view->origem ?>', situacao:'exclui'});
                  }
              })
            } else {
              swal('', 'Há família sem Participação escolhida!', 'error');  
            }
          }
      }

      function coletaDadosI(){
         var ids = document.getElementsByClassName('familiaEscolhida');
         coletaIDsI(ids);         
      };  
              
      function coletaIDsI(dados){
        var array_dados = dados; 
        var newArray = [];

        for(var x = 0; x <= array_dados.length; x++){     
            if(typeof array_dados[x] == 'object'){
              if(array_dados[x].checked){
                newArray.push(array_dados[x].id);
              }          
            }
         }   

         if(newArray.length <= 0  || newArray == ''){
            var fml_escolhida = '';
         } 

         /*
        // Para dar display no Console em javascript
        $('document').ready(function() {
          console.log(newArray, newArray.length);
        });
        */
        
         if (fml_escolhida == '') {
            swal('', 'Não há família escolhida!', 'warning');

         } else {

            var remetePost = 1;

            for (var p = 0; p < newArray.length; p++) {
              var fml_sn_escolhida = newArray[p];
              fml_sn_escolhida = fml_sn_escolhida.split(';');
              var fml_escolhida = fml_sn_escolhida[0]
              var sn_escolhido = fml_sn_escolhida[1]

              if (sn_escolhido == 's') {
                remetePost = 0;
                break;
              }
            }

            if (remetePost == 1) {
              swal({
                  title: '',
                  text: 'Confirma a inclusão da família na Solicitação?',
                  type: 'warning',                  //"warning", "error", "success", "info"
                  showCancelButton: true,
                  confirmButtonColor: '#3085d6',
                  cancelButtonColor: '#D80C1B',
                  confirmButtonText: 'Sim',
                  cancelButtonText: 'Não',
                  closeOnClickOutside: false

                }, function(isConfirm) {
                  if (isConfirm) {
                     sendPost('/recFinanFamiliaVincularBase', {cb_grupo_escolhido:'<?= $this->view->codGrupo ?>', nome_grupo:'<?= $this->view->nomeGrupo ?>', cb_subgrupo_escolhido:'<?= $this->view->codSubgrupo ?>', nome_subgrupo:'<?= $this->view->nomeSubgrupo ?>', seql_pedido_finan:'<?= $this->view->seqlPedidoFinan ?>', familia_escolhida:newArray, origem:'<?= $this->view->origem ?>', situacao:'inclui'});
                  }
              })
            } else {
              swal('', 'Há família já Participando escolhida!', 'error');  
            }
          }
      }

    </script>
  </body>
</html>