<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Vinculação de voluntário a grupo e subgrupo
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/subgrupoVincularVoluntarioBase" method="post" id="FormVincula">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Vincular Voluntário a Grupo/Subgrupo</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_grupo_escolhido">Grupo<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="cb_grupo_escolhido" name="cb_grupo_escolhido" class="form-control">
                    <option value="">Escolha Grupo</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_subgrupo_escolhido">Subgrupo</label>  
                <div class="col-md-4">
                  <select id="cb_subgrupo_escolhido" name="cb_subgrupo_escolhido" class="form-control">
                    <option value="">Escolha Subgrupo</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="voluntario_escolhido">Voluntário<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="voluntario_escolhido" name="voluntario_escolhido" class="form-control">

                    <?php function selected( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <!-- Para simular "placeholder" no combobox -->
                    <option value="">Escolha Voluntário</option> 

                    <?php foreach ($this->view->voluntarios as $indice => $volunt) { ?>
                      <?php if ($indice == 0) { ?>
                        <option value="<?= $volunt['cd_vlntID'] ?>"<?php echo selected($volunt['cd_vlntID'], $this->view->vinculo['voluntario_escolhido']); ?>><?= $volunt['nm_vlnt'] ?></option>
                      <?php } else { ?>
                        <option value="<?= $volunt['cd_vlntID'] ?>"<?php echo selected($volunt['cd_vlntID'], $this->view->vinculo['voluntario_escolhido']); ?>><?= $volunt['nm_vlnt'] ?></option>
                      <?php } ?>                                                  
                    <?php } ?>  
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="atuacao_escolhida">Perfil de Atuação<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="atuacao_escolhida" name="atuacao_escolhida" class="form-control">
                    <?php function selected1( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <!-- Para simular "placeholder" no combobox -->
                    <option value=""<?php echo selected1('', $this->view->vinculo['atuacao_escolhida']); ?>>Escolha Perfil</option>
                    
                    <option value="1"<?php echo selected1('1', $this->view->vinculo['atuacao_escolhida']); ?>>Coordenador Cadastral</option>
                    <option value="2"<?php echo selected1('2', $this->view->vinculo['atuacao_escolhida']); ?>>Coordenador Financeiro</option>
                    <option value="3"<?php echo selected1('3', $this->view->vinculo['atuacao_escolhida']); ?>>Coordenador Revisor</option>
                    <option value="4"<?php echo selected1('4', $this->view->vinculo['atuacao_escolhida']); ?>>Coordenador Geral</option>
                    <option value="5"<?php echo selected1('5', $this->view->vinculo['atuacao_escolhida']); ?>>Voluntário Normal</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Vincular"></label>
                <div class="col-md-8">
                  <!--<button class="btn btn-primary" id="btnBuscar" type="Submit" disabled="">Vincular</button>-->
                  <button class="btn btn-primary" id="btnBuscar" type="button" disabled="">Vincular</button>

                  <a href="/voluntario" class="btn btn-success" >Retorna</a>
                  
                  <a class="btn" id="btnGrupo"></a>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
             <small class="form-text text-danger">Vinculação realizada com Sucesso!</small>
        
          <?php } else if ($this->view->erroValidacao == 2) { ?>
             <small class="form-text text-danger">Grupo, voluntário e Perfil precisam ser escolhidos!</small>

          <?php } else if ($this->view->erroValidacao == 3) { ?>
             <small class="form-text text-danger">Vinculo já existente para este Voluntário neste Grupo <?php echo ' '.$this->view->grupoTratado. '!' ?> </small>

          <?php } else if ($this->view->erroValidacao == 4) { ?>
             <small class="form-text text-danger">Vinculo já existente para este Voluntário neste Grupo/Subgrupo!</small>
             
             <small class="form-text text-danger"><?php echo 'Grupo: '.$this->view->grupoTratado ?> </small>

             <small class="form-text text-danger"><?php echo 'Subgrupo: '.$this->view->subgrupoTratado ?></small>

          <?php } ?>
        </div>

      </div>
    </section>

    <script type="text/javascript">
      // Para simular o clique do botão e abrir as opções de Grupo e Subgrupo
      <?php if ($this->view->erroValidacao >= 0 ) { ?>
        $(function() {
            $('#btnGrupo').on("click", function () {
              $('#btnGrupo').hide();
          });
          // Chama a função de clique através do trigger
          $("#btnGrupo").trigger('click');
        })
      <?php } ?>

      $('#btnGrupo').click(function(e){
          $("#btnBuscar").removeAttr("disabled");
          $("#cb_grupo_escolhido").removeAttr("disabled");
          $("#cb_subgrupo_escolhido").removeAttr("disabled");
          $('#cb_grupo_escolhido').empty().append('<option>Escolha Grupo</option>>');
          $('#cb_subgrupo_escolhido').empty().append('<option>Escolha Subgrupo</option>');

          // Carrega Grupos          
          $.getJSON('ConsultaCbDependente.php?opcao=grupo', function (dados){

             if (dados.length > 0){    
                var option = '<option>Escolha Grupo</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_grupo+'">'+obj.nome_grupo+'</option>';
                })
              }else{
                 Reset();
             }
             $('#cb_grupo_escolhido').html(option).show();
          })
      })

      // Carrega Subgrupos
      $('#cb_grupo_escolhido').change(function(e){
        var grupo = $('#cb_grupo_escolhido').val();
          $.getJSON('ConsultaCbDependente.php?opcao=subgrupo&valor='+grupo, 
          function (dados){ 
           
             if (dados.length > 0){    
                var option = '<option>Escolha Subgrupo</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_subgrupo+'">'+obj.nome_subgrupo+'</option>';
                })
              }else{
                Reset(); 
             }

             $('#cb_subgrupo_escolhido').html(option).show(); 
          })
      })

      // <!-- Resetar Selects --> //
      function Reset(){
        $('#cb_grupo_escolhido').empty().append('<option>Escolha Grupo</option>>');
        $('#cb_subgrupo_escolhido').empty().append('<option>Escolha Subgrupo</option>');

        <?php if ($this->view->erroValidacao >= 0 ) { ?>
          $(function() {
              $('#btnGrupo').on("click", function () {
                $('#btnGrupo').hide();
            });
            // Chama a função de clique através do trigger
            $("#btnGrupo").trigger('click');
          })
        <?php } ?>
      }
    </script>  

    <script src="alertaConfirmaVincula.js"></script>
  </body>
</html>