<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Consulta efetiva dos dados do voluntário
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta de Voluntário DPS</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Código</label>  
                <div class="col-md-6">
                  <input id="codigo" name="codigo" placeholder="" class="form-control input-md" type="text" maxlength="100" disabled="" required="" value="<?= $this->view->voluntario['codigo'] ?>">

                  <!-- Para poder retornar no $_POST o valor do name="codigo", pois está disabled acima -->
                  <input type="hidden" name="codigo" value=<?= $this->view->voluntario['codigo'] ?>> 
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Nome<h11>*</h11></label>  
                <div class="col-md-6">
                  <input id="nome" name="nome" placeholder="" class="form-control input-md" required="" type="text" maxlength="100" autofocus value="<?= $this->view->voluntario['nome'] ?>" disabled="">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Nome Fórum</label>  
                <div class="col-md-6">
                  <input id="nomeforum" name="nomeforum" class="form-control input-md" type="text" maxlength="100" value="<?= $this->view->voluntario['nomeforum'] ?>" disabled="">
                </div>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Nr. Sócio Comunhão</label>  
                <div class="col-lg-2">
                  <input id="nrsocio" name="nrsocio" class="form-control input-md" type="text" maxlength="11" pattern="[0-9]+$" value="<?= $this->view->voluntario['nrsocio'] ?>" disabled="">
                </div>

                <label class="col-md-2 control-label" for="Nome">Nr. Identidade</label>  
                <div class="col-lg-2">
                  <input id="nridentidade" name="nridentidade" class="form-control input-md" type="text" maxlength="15" pattern="[0-9]+$" value="<?= $this->view->voluntario['nridentidade'] ?>" disabled="">
                </div>
              </div>
                
              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">CPF</label>  
                <div class="col-lg-2">
                  <input id="cpf" name="cpf" class="form-control input-md" type="text" maxlength="11" minlength="11" onkeypress="$(this).mask('000.000.000-00');" disabled="" value=<?= $this->view->voluntario['cpf'] ?>>
                </div>
                
                <label class="col-md-2 control-label" for="Nome">Nascimento</label>  
                <div class="col-lg-2">
                  <input id="dtnasc" name="dtnasc" class="form-control input-md" type="text" maxlength="10" onkeypress="$(this).mask('00/00/0000')" onBlur="showhide()" disabled="" value=<?= $this->view->voluntario['dtnasc'] ?>>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="prependedtext">Naturalidade</label>
                <div class="col-lg-2">
                  <div class="input-group">     
                  <input id="naturalidade" name="naturalidade" class="form-control" type="text" maxlength="20" value="<?= $this->view->voluntario['naturalidade'] ?>" disabled="">
                  </div>
                </div> 

                <label class="col-md-2 control-label" for="EstadoUF">Estado (UF)</label>  
                <div class="col-lg-3">
                  <select id="EstadoUF" name="estadoUF" class="form-control" disabled="disabled">                        
                    <?php function selected( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <option value=""<?php echo selected('', $this->view->voluntario['estadoUF']); ?>></option>
                    <option value="AC"<?php echo selected('AC', $this->view->voluntario['estadoUF']); ?>>Acre</option>
                    <option value="AL"<?php echo selected('AL', $this->view->voluntario['estadoUF']); ?>>Alagoas</option>
                    <option value="AP"<?php echo selected('AP', $this->view->voluntario['estadoUF']); ?>>Amapá</option>
                    <option value="AM"<?php echo selected('AM', $this->view->voluntario['estadoUF']); ?>>Amazonas</option>
                    <option value="BA"<?php echo selected('BA', $this->view->voluntario['estadoUF']); ?>>Bahia</option>
                    <option value="CE"<?php echo selected('CE', $this->view->voluntario['estadoUF']); ?>>Ceará</option>
                    <option value="DF"<?php echo selected('DF', $this->view->voluntario['estadoUF']); ?>>Distrito Federal</option>
                    <option value="ES"<?php echo selected('ES', $this->view->voluntario['estadoUF']); ?>>Espirito Santo</option>
                    <option value="GO"<?php echo selected('GO', $this->view->voluntario['estadoUF']); ?>>Goiás</option>
                    <option value="MA"<?php echo selected('MA', $this->view->voluntario['estadoUF']); ?>>Maranhão</option>
                    <option value="MT"<?php echo selected('MT', $this->view->voluntario['estadoUF']); ?>>Mato Grosso</option>
                    <option value="MS"<?php echo selected('MS', $this->view->voluntario['estadoUF']); ?>>Mato Grosso Sul</option>
                    <option value="MG"<?php echo selected('MG', $this->view->voluntario['estadoUF']); ?>>Minas Gerais</option>
                    <option value="PA"<?php echo selected('PA', $this->view->voluntario['estadoUF']); ?>>Pará</option>
                    <option value="PB"<?php echo selected('PB', $this->view->voluntario['estadoUF']); ?>>Paraíba</option>
                    <option value="PR"<?php echo selected('PR', $this->view->voluntario['estadoUF']); ?>>Paraná</option>
                    <option value="PE"<?php echo selected('PE', $this->view->voluntario['estadoUF']); ?>>Pernambuco</option>
                    <option value="PI"<?php echo selected('PI', $this->view->voluntario['estadoUF']); ?>>Piaui</option>
                    <option value="RJ"<?php echo selected('RJ', $this->view->voluntario['estadoUF']); ?>>Rio de Janeiro</option>
                    <option value="RN"<?php echo selected('RN', $this->view->voluntario['estadoUF']); ?>>Rio Grande do Norte</option>
                    <option value="RS"<?php echo selected('RS', $this->view->voluntario['estadoUF']); ?>>Rio Grande do Sul</option>
                    <option value="RO"<?php echo selected('RO', $this->view->voluntario['estadoUF']); ?>>Rondonia</option>
                    <option value="RR"<?php echo selected('RR', $this->view->voluntario['estadoUF']); ?>>Roraima</option>
                    <option value="SC"<?php echo selected('SC', $this->view->voluntario['estadoUF']); ?>>Santa Catarina</option>
                    <option value="SP"<?php echo selected('SP', $this->view->voluntario['estadoUF']); ?>>São Paulo</option>
                    <option value="SE"<?php echo selected('SE', $this->view->voluntario['estadoUF']); ?>>Sergipe</option>
                    <option value="TO"<?php echo selected('TO', $this->view->voluntario['estadoUF']); ?>>Tocantins</option>

                  </select>
                </div>
              </div>
              
              <div class="form-group">
                <label class="col-md-2 control-label" for="radios">Sexo <h11>*</h11></label>
                <div class="col-md-4"> 
                  <div class="input-group">       
                    <label class="radio-inline" for="radios-0" >
                    <input name="sexo" id="sexo" value="feminino" disabled="" type="radio" required <?php echo ($this->view->voluntario['sexo'] == "feminino") ? "checked" : null; ?>/>Feminino
                    </label> 
                    <label class="radio-inline" for="radios-1">
                    <input name="sexo" id="sexo" value="masculino" disabled="" type="radio" required <?php echo ($this->view->voluntario['sexo'] == "masculino") ? "checked" : null; ?>/>Masculino
                    </label>
                  </div>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="prependedtext">Comercial</label>
                <div class="col-lg-3">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                    <input id="fonecomercial" name="fonecomercial" class="form-control" type="text" maxlength="15" onkeypress="$(this).mask('(00) 0000-0009')" disabled="" value="<?= $this->view->voluntario['fonecomercial'] ?>">
                  </div>
                </div>
                
                <label class="col-md-1 control-label" for="prependedtext">Residencial</label>
                <div class="col-lg-3">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                    <input id="foneresidencial" name="foneresidencial" class="form-control" type="text" maxlength="15"  onkeypress="$(this).mask('(00) 0000-0009')" disabled="" value="<?= $this->view->voluntario['foneresidencial'] ?>">
                  </div>
                </div>
              </div>

              <div class="form-group">                
                <label class="col-md-2 control-label" for="prependedtext">Celular</label>
                <div class="col-lg-3">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                    <input id="celular" name="celular" class="form-control" disabled="" type="text" maxlength="15"  onkeypress="$(this).mask('(00) 00000-0009')" value="<?= $this->view->voluntario['celular'] ?>">
                  </div>
                </div>
              </div> 

              <div class="form-group">
                <label class="col-md-2 control-label" for="prependedtext">Email <h11>*</h11></label>
                <div class="col-lg-5">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    <input id="email" name="email" class="form-control" disabled="" placeholder="email@email.com" required="" type="text" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" maxlength="100" value="<?= $this->view->voluntario['email'] ?>">
                  </div>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="CEP">CEP</label>
                <div class="col-lg-2">
                  <input id="cep" name="cep" class="form-control input-md" type="text" maxlength="8" minlength="8" onkeypress="$(this).mask('00.000-000')" disabled="" value="<?= $this->view->voluntario['cep'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="CEP">Endereço</label>
                <div class="col-lg-4">
                  <input id="endereco" name="endereco" disabled="" class="form-control input-md" type="text" maxlength="100" value="<?= $this->view->voluntario['endereco'] ?>">
                </div>

                <label class="col-md-2 control-label" for="RA">Região Administrativa</label>
                <div class="col-lg-3">
                  <select id="ra_escolhida" name="ra_escolhida" class="form-control" disabled="disabled">
                      <!-- Monta o combobox - Foca no registro recebido -->
                      <?php function selected2( $value, $selected ) {
                          return $value==$selected ? ' selected="selected"' : ''; } ?>
                      <?php foreach ($this->view->regioes as $indice_ra => $regiao) { ?>
                        <?php if ($indice_ra == 0) { ?>
                          <option value=""></option>  
                          <option value="<?= $regiao['cod_ra'] ?>"<?php echo selected2($regiao['cod_ra'], $this->view->voluntario['ra_escolhida']); ?>><?= $regiao['nome_ra'] ?></option>
                        <?php } else { ?>
                          <option value="<?= $regiao['cod_ra'] ?>"<?php echo selected2($regiao['cod_ra'], $this->view->voluntario['ra_escolhida']); ?>><?= $regiao['nome_ra'] ?></option>
                        <?php } ?>  
                      <?php } ?>  
                  </select>
                </div>
              </div>

              <div class="form-group">    
                <label class="col-md-2 control-label" for="Escolaridade">Escolaridade</label>
                <div class="col-lg-3">
                  <select id="escolaridade" name="escolaridade" class="form-control" disabled="disabled">
                    
                    <?php function selected1( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>
                    
                    <option value=""<?php echo selected('', $this->view->voluntario['escolaridade']); ?>></option>
                    <option value="Analfabeto"<?php echo selected1('Analfabeto', $this->view->voluntario['escolaridade']); ?>>Analfabeto</option>
                    <option value="Fundamental Incompleto"<?php echo selected1('Fundamental Incompleto', $this->view->voluntario['escolaridade']); ?>>Fundamental Incompleto</option>
                    <option value="Fundamental Completo"<?php echo selected('Fundamental Completo', $this->view->voluntario['escolaridade']); ?>>Fundamental Completo</option>
                    <option value="Médio Incompleto"<?php echo selected('Médio Incompleto', $this->view->voluntario['escolaridade']); ?>>Médio Incompleto</option>
                    <option value="Médio Completo"<?php echo selected('Médio Completo', $this->view->voluntario['escolaridade']); ?>>Médio Completo</option>
                    <option value="Superior Incompleto"<?php echo selected('Superior Incompleto', $this->view->voluntario['escolaridade']); ?>>Superior Incompleto</option>
                    <option value="Superior Completo"<?php echo selected('Superior Completo', $this->view->voluntario['escolaridade']); ?>>Superior Completo</option>
                    <option value="Especialização"<?php echo selected('Especialização', $this->view->voluntario['escolaridade']); ?>>Especialização</option>
                    <option value="Mestrado"<?php echo selected('Mestrado', $this->view->voluntario['escolaridade']); ?>>Mestrado</option>
                    <option value="Doutorado"<?php echo selected('Doutorado', $this->view->voluntario['escolaridade']); ?>>Doutoradossss</option>
                  </select>
                </div>

                <label class="col-md-2 control-label" for="profissao">Profissão</label>  
                <div class="col-lg-4">
                  <input id="profissao" name="profissao" type="text" disabled="" placeholder="" class="form-control input-md" maxlength="50" value="<?= $this->view->voluntario['profissao'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="encaminhamento">Estudo Sistemático da Doutrina Espíria (ESDE)<h11>*</h11></label>
                <div class="col-md-4">
                  <div class="input-group">       
                    <label class="radio-inline" for="radios-0">
                    <input type="radio" name="esde" id="esde" value="nao" disabled="" required <?php echo ($this->view->voluntario['esde'] == "nao") ? "checked" : null; ?>/>Não
                    </label> 
                    <label class="radio-inline" for="radios-1">
                    <input type="radio" name="esde" id="esde" value="sim" disabled="" required <?php echo ($this->view->voluntario['esde'] == "sim") ? "checked" : null; ?>/>Sim
                    </label>
                  </div>
                </div>
              
                <label class="col-md-2 control-label" for="prependedtext">Descrição Fase ESDE</label>
                <div class="col-lg-3">
                  <div class="input-group">     
                    <input id="descfaseesde" name="descfaseesde" class="form-control" type="text" maxlength="100" disabled="" value="<?= $this->view->voluntario['descfaseesde'] ?>">
                  </div>
                </div>
              </div>
                    
              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Dia Semana para Atuação</label>  
                <div class="col-lg-2">
                  <input id="diasemana" name="diasemana" disabled="" class="form-control input-md" type="text" maxlength="15" value="<?= $this->view->voluntario['diasemana'] ?>" >
                </div>

                <label class="col-md-2 control-label" for="Nome">Horário de Atuação</label>  
                <div class="col-lg-2">
                  <input id="horario" name="horario" disabled="" class="form-control input-md" type="text" maxlength="20" value="<?= $this->view->voluntario['horario'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Outra Atividade Voluntariado</label>  
                <div class="col-lg-6">
                  <input id="outraatividade" name="outraatividade" disabled="" class="form-control input-md" type="text" maxlength="100" value="<?= $this->view->voluntario['outraatividade'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Conhecimentos Específicos</label>  
                <div class="col-lg-6">
                  <input id="conhecimentoespecifico" name="conhecimentoespecifico" class="form-control input-md" type="text" maxlength="100" disabled="" value="<?= $this->view->voluntario['conhecimentoespecifico'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Atividade de Preferência voluntariado</label>  
                <div class="col-md-6">
                  <input id="atividadepreferencia" name="atividadepreferencia" class="form-control input-md" type="text" maxlength="100" disabled="" value="<?= $this->view->voluntario['atividadepreferencia'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Habilidades</label>  
                <div class="col-md-9">
                  <input id="habilidades" name="habilidades" disabled="" class="form-control input-md" type="text" maxlength="100" value="<?= $this->view->voluntario['habilidades'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Observação</label>  
                <div class="col-md-9">
                  <input id="observacao" name="observacao" disabled="" class="form-control input-md" type="text" maxlength="200" value="<?= $this->view->voluntario['observacao'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                 
                  <?php if ($this->view->voluntario['rotaV'] == 'cv') { ?>
                    <!--Retorna para consulta normal de Voluntário na Aba Voluntário -->
                    <a href="/voluntarioConsultar" class="btn btn-success">Retorna</a>
                  
                  <?php } else { ?>  <!-- 'cvvgs' -->
                    <!--Retorna para consulta de Vínculo Voluntário com Grupo e Subgrupo -->
                    <a class="btn btn-success" href="#" onclick="sendPost('/subgrupoConsultarVinculoVoluntarioMenu', {dt_inc:'<?= $_POST['dt_inc'] ?>', dt_fim:'<?= $_POST['dt_fim'] ?>', cb_grupo_escolhido:'<?= $_POST['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $_POST['cb_subgrupo_escolhido'] ?>'});">Retorna</a>

                  <?php } ?>
              
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>
      </div>
    </section>

    <!-- Para formatar campos de entrada no formulário- não pode ficar em "layout.pthml" pois não executava -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <!-- Para Possibilitar $_POST -->
    <script src="sendPost.js"></script>
  </body>
</html>