<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu para alteração efetiva de Nível de acesso ou senha do voluntário
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css"> 
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/voluntarioAlterarNASBase" method="post" id="FormAltera"> 
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Alteração de Nível de Acesso e/ou Senha - Voluntário DPS</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11>Campo Obrigatório</p>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Código</label>  
                <div class="col-md-6">
                  <input id="codigo" name="codigo" placeholder="" class="form-control input-md" type="text" maxlength="100" disabled="" value="<?= $this->view->voluntario['codigo'] ?>">

                  <!-- Para poder retornar no $_POST o valor do name="codigo", pois está disabled acima -->
                  <input type="hidden" name="codigo" value="<?= $this->view->voluntario['codigo'] ?>"> 
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Nome">Nome</label>  
                <div class="col-md-6">
                    <input id="nome" name="nome" placeholder="" class="form-control input-md" disabled="" type="text" maxlength="100"  value="<?= $this->view->voluntario['nome'] ?>">

                    <!-- Para poder retornar no $_POST o valor do name="codigo", pois está disabled acima -->
                    <input type="hidden" name="nome" value="<?= $this->view->voluntario['nome'] ?>"> 
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Email">Email</label>  
                <div class="col-md-6">
                    <input id="email" name="email" placeholder="" class="form-control input-md" disabled="" type="text" maxlength="100"  value="<?= $this->view->voluntario['email'] ?>">

                    <!-- Para poder retornar no $_POST o valor do name="codigo", pois está disabled acima -->
                    <input type="hidden" name="email" value="<?= $this->view->voluntario['email'] ?>"> 
                </div>
              </div>

              <div class="form-group">    
                <label class="col-md-2 control-label" for="nivelAcesso">Nível de Acesso<h11>*</h11></label>
                <div class="col-lg-3">
                  <select id="nivelAcesso" name="nivelAcesso" class="form-control">
                    
                    <?php function selected1( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>
                    <option value="Administrador Geral"<?php echo selected1('Administrador Geral', $this->view->voluntario['nivelAcesso']); ?>>Administrador Geral</option>
                    <option value="Administrador"<?php echo selected1('Administrador', $this->view->voluntario['nivelAcesso']); ?>>Administrador</option>
                    <option value="Usuario"<?php echo selected1('Usuario', $this->view->voluntario['nivelAcesso']); ?>>Usuário</option>
                  </select>
                </div>
              </div>
                    
              <div class="form-group">
                <label class="col-md-2 control-label" for="Senha">Senha<h11>**</h11></label>  
                <div class="col-lg-2">
                  <input id="senha" name="senha" placeholder="" class="form-control input-md" type="password" maxlength="15" value="" >
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="SenhaConfirma">Senha Confirmação<h11>**</h11></label>  
                <div class="col-lg-2">
                  <input id="senhaConfirma" name="senhaConfirma" placeholder="" class="form-control input-md" type="password" maxlength="15" value="" >
                </div>
              </div>

              <!-- Os dois campos abaixo não aparecem na tela, servirão para no retorno serem tratados -->
              <div class="form-group">
                <label class="col-md-2 control-label" for="sequencialLogin"></label>  
                <div class="col-md-6">
                    <input id="sequencialLogin" name="sequencialLogin" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->voluntario['sequencialLogin'] ?>" hidden>

                    <!-- Para poder retornar no $_POST o valor do name="codigo", pois está disabled acima -->
                    <input type="hidden" name="sequencialLogin" value="<?= $this->view->voluntario['sequencialLogin'] ?>"> 
                </div>

                <label class="col-md-2 control-label" for="nivelAcessoCompara"></label>  
                <div class="col-md-6">
                    <input id="nivelAcessoCompara" name="nivelAcessoCompara" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->voluntario['nivelAcessoCompara'] ?>" hidden>

                    <!-- Para poder retornar no $_POST o valor do name="codigo", pois está disabled acima -->
                    <input type="hidden" name="nivelAcessoCompara" value="<?= $this->view->voluntario['nivelAcessoCompara'] ?>"> 
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Alterar"></label>
                <div class="col-md-8">
                  <button class="btn btn-primary" type="button" id="btnAlterar">Alterar</button>

                  <a href="/voluntarioAlterarNAS" class="btn btn-success">Retorna</a>
                </div>
              </div>

              <div class="col-md-11 control-label fg-primary">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>**</h11>Se não for trocar a senha, deixar em branco!</p>
              </div>

            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
             <small class="form-text text-danger">Erro: Senhas não Conferem! Verifique!</small>

          <?php } else if ($this->view->erroValidacao == 2) { ?>
             <small class="form-text text-danger">Erro: Não houve alteração dos Dados!</small>

          <?php } else if ($this->view->erroValidacao == 9) { ?>
             <small class="form-text text-danger">Erro: <?php echo ' '.$this->view->erroException ?>Verifique!</small>
          <?php } ?>
        </div>

      </div>
    </section>

    <!-- Para formatar campos de entrada no formulário- não pode ficar em "layout.pthml" pois não executava -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <!-- Para mostrar Alerta de Confima ou Não -->
    <script src="alertaConfirmaAltera.js"></script>
  </body>
</html>