<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de escolher voluntário para consulta
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/voluntarioConsultarMenu" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta de Voluntário DPS</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-md-2 control-label" for="voluntario_escolhido">Voluntário</label>  
                <div class="col-lg-4">
                  <select required id="voluntario_escolhido" name="voluntario_escolhido" class="form-control">
                    <?php foreach ($this->view->voluntarios as $indice => $voluntario) { ?>
                      <option value=<?= $voluntario['cd_vlntID'] ?>><?= $voluntario['nm_vlnt'] ?></option>
                    <?php } ?>  
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="/voluntario" class="btn btn-success" >Retorna</a>

                  <button class="btn btn-primary" type="Submit">Buscar</button>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>
      </div>
    </section>
  </body>
</html>