<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu para alteração de senha do próprio voluntario logado
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/voluntarioSenhaNova" method="post" id="FormAltera">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Alteração de Senha</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-md-2 control-label" for="senhaAtual">Senha Atual</label>  
                <div class="col-md-4">
                  <input type="password" id="1" name="senhaAtual" class="form-control" required="" placeholder="Digite a senha Atual" maxlength="32" autofocus >
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="senhaNova">Nova Senha</label>  
                <div class="col-md-4">
                  <input type="password" id="2" name="senhaNova" class="form-control" required="" placeholder="Digite a nova senha" onclick="this.style.borderColor=''">              
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="senhaNovaRedigita">Nova Senha Confirma</label>  
                <div class="col-md-4">
                          <input type="password" id="3" name="senhaNovaRedigita" class="form-control" required="" placeholder="Confirme a nova senha" onclick="this.style.borderColor=''">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="/menuPrincipal" class="btn btn-success">Retorna</a>

                  <button class="btn btn-primary" type="button" id="btnAlterar">Salvar</button>
                </div>
              </div>
			
            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center">
            <?php if ($this->view->erroSenha == 1) { ?>
               <small class="form-text text-danger">Erro: Senha Atual menor que 3 caracteres! Verifique!</small>
            <?php } else if ($this->view->erroSenha == 2) { ?>
              <small class="form-text text-danger">Erro: Nova Senha menor que 3 caracteres! Verifique!</small>
            <?php } else if ($this->view->erroSenha == 3) { ?>
              <small class="form-text text-danger">Erro: Nova Senha de Confirmação menor que 3 caracteres! Verifique!</small>
            <?php } else if ($this->view->erroSenha == 4) { ?>
              <small class="form-text text-danger">Erro: Senha Atual não confere! Verifique!</small>
            <?php } else if ($this->view->erroSenha == 5) { ?>
              <small class="form-text text-danger">Erro: Nova Senha e Senha Confirmada diferentes! Verifique!</small>
            <?php } else if ($this->view->erroSenha == 6) { ?>
              <small class="form-text text-danger">Erro: Nova Senha igual a Senha Atual! Verifique!</small>
            <?php } else if ($this->view->erroSenha == 0) { ?>
              <small class="form-text text-danger">Senha Alterada com Sucesso!</small>
            <?php } ?>
        </div>

      </div>
    </section>
    
    <!-- Para mostrar Alerta de Confima ou Não -->
    <script src="alertaConfirmaAltera.js"></script>
  </body>
</html>