<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com lista de famílias que podem ter sido atendidas antes tendo este solicitante como membro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Recursos Financeiros DPS</h4></div>
          <div class="panel-body">

            <div class="col-md-12 control-label text-center">
              <?php if ($this->view->erroValidacao == 2) { ?>
                <small class="form-text" style="background-color: #69C8E0; color: white; font-size: 100%">Inclusão de Valor de Recurso Realizada com Sucesso!</small>

                <p class="form-text text-danger">&nbsp</p>
                
              <?php } else if ($this->view->erroValidacao == 4) { ?>
                <small class="form-text" style="background-color: #69C8E0; color: white; font-size: 100%">Alteração de Valor de Recurso Realizada com Sucesso!</small>

                <p class="form-text text-danger">&nbsp</p>
                
              <?php } else if ($this->view->erroValidacao == 5) { ?>
                <small class="form-text" style="background-color: #69C8E0; color: white; font-size: 100%">Cancelamento de Valor de Recurso Realizado com Sucesso!</small>

                <p class="form-text text-danger">&nbsp</p>
                
              <?php } else if ($this->view->erroValidacao == 0) { ?>
                <p class="form-text text-danger">&nbsp</p>

              <?php } ?>
            </div>
            
            <div class="col-md-12 d-flex">
              <ul class="list-group">
                <label class="list-group-item list-group-item-info bg-warning">Saldo Recursos (R$): <?php echo $this->view->saldoORC ?></label>  
              </ul>
            </div>

            <div class="table-responsive-lg">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Seql Recurso</th>
                  <th scope="col">Data Inclusão Recurso</th>
                  <th scope="col">Valor Recurso (R$)</th>
                  <th scope="col">Valor Saldo Recurso (R$)</th>
                  <th scope="col">Observação</th>
                  <th scope="col">Responsável Cadastramento</th>
                  <?php if ($this->view->temRecurso == 1) { ?>
                    <th scope="col">Selecione p/Gerenciar Recurso</th>                  
                  <?php } ?>                    
                </tr>
                </thead>
                
                <tbody>
                    <?php foreach ($this->view->dadosORC as $indice => $orc) { ?>
                      <tr>
                        <td class="text-center"><?php echo $orc['seql_orc']; ?></td>

                        <td class="text-center"><?php echo $orc['dt_recur_orc']; ?></td>

                        <td class="text-right"><?php echo $orc['vlr_recur_orc']; ?></td>
                        
                        <td  class="text-right"><?php echo $orc['vlr_sdo_recur_orc']; ?></td>

                        <!-- Para definir largura fixa da coluna -->
                        <td class="larguraColunaPedidoResumido"><?php echo $orc['obs']; ?></td>

                        <td><?php echo $orc['nm_vlnt_resp_incl']; ?></td>

                        <?php if ($this->view->temRecurso == 1) { ?>
                          <!-- Checkbox para assinalar o recurso a ser gerenciado -->
                          <td class="text-center"><input class="recursoEscolhido link-check" type="checkbox" id='<?= $orc['seql_orc'] ?>' value="01" onchange="cbChange(this)"></td>
                        <?php } ?>  
                      </tr>
                    <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">
                <a href="/recFinanDPSRecurso" class="btn btn-success" >Retorna</a>

                <a class="btn btn-primary" href="#" onclick="chamaInsereDados()">Incluir Recurso</a>

                <?php if ($this->view->temRecurso == 1) { ?>
                  <a class="btn btn-danger" href="#" onclick="coletaDados()">Gerenciar Recurso</a>
                <?php } ?>  

              </div>
            </div>

          </div>
        </div>
       </form>
      </div>
    </section>

    <script src="sendPost.js"></script>

    <script>
      // Para obter os cd_fml marcados no Checkbox (No caso só permitiremos um) //
      function coletaDados(){
         var ids = document.getElementsByClassName('recursoEscolhido');
         coletaIDs(ids);         
      };  
              
      function coletaIDs(dados){
         var array_dados = dados; 
         var newArray = [];
         for(var x = 0; x <= array_dados.length; x++){     
              if(typeof array_dados[x] == 'object'){
                if(array_dados[x].checked){
                   newArray.push(array_dados[x].id)          
                }          
              }
         }   

         if(newArray.length <= 0 || newArray == ''){
            var recurso_escolhido = '';
         
         } else {
            var recurso_escolhido = newArray[0];
         }

         if (recurso_escolhido == '') {
            swal('', 'Não há Recurso escolhido!', 'warning');
         
         } else {
           sendPost('/recFinanDPSRecursoRealGerencia', {seql_orc:recurso_escolhido, origem:'gerenciamento'});
         }
      };

      function chamaInsereDados(){
         sendPost('/recFinanDPSRecursoRealMenu', {origem:'inclusao'});         
      };  

      // Para possibiliar que se selecione apenas um checkbox //
      function cbChange(obj) {
        var cbs = document.getElementsByClassName("link-check");
        for (var i = 0; i < cbs.length; i++) {
           if(cbs[i] !== obj) cbs[i].checked = false;
         }
      }

    </script>
  </body>
</html>