<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com lista de famílias que podem ter sido atendidas antes tendo este solicitante como membro
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Recurso Financeiro DPS - Valor Mínimo de Referência (VMR)</h4></div>
          <div class="panel-body">

            <div class="col-md-12 control-label text-center">
              <?php if ($this->view->erroValidacao == 2) { ?>
                <small class="form-text" style="background-color: #69C8E0; color: white; font-size: 100%">Inclusão de Valor Realizada com Sucesso!</small>

                <p class="form-text text-danger">&nbsp</p>

              <?php } else if ($this->view->erroValidacao == 3) { ?>
                <small class="form-text" style="background-color: red; color: white; font-size: 100%">Erro: Valor impostado igual ao valor atual!</small>

                <p class="form-text text-danger">&nbsp</p>
                
              <?php } else if ($this->view->erroValidacao == 0) { ?>
                <p class="form-text text-danger">&nbsp</p>

              <?php } ?>
            </div>

            <div class="table-responsive-lg">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Seql VMR</th>
                  <th scope="col">Valor Referência (R$)</th>
                  <th scope="col">Data Início Vigência</th>
                  <th scope="col">Data Final Vigência</th>
                  <th scope="col">Observação</th>
                  <th scope="col">Responsável Cadastramento</th>
                  <th scope="col">Situação</th>
                </tr>
                </thead>
                
                <tbody>
                    <?php foreach ($this->view->dadosVMR as $indice => $vmr) { ?>
                      <tr>
                        <td><?php echo $vmr['seql_vlr_minimo_ref']; ?></td>

                        <td><?php echo $vmr['vlr_minimo_ref']; ?></td>

                        <td><?php echo $vmr['dt_inc_vgc']; ?></td>
                        
                        <td><?php echo $vmr['dt_fim_vgc']; ?></td>

                        <!-- Para definir largura fixa da coluna -->
                        <td class="larguraColunaPedidoResumido"><?php echo $vmr['obs']; ?></td>

                        <td><?php echo $vmr['nm_vlnt_resp_incl']; ?></td>

                        <td><?php echo $vmr['nm_est_vlr_minimo_ref']; ?></td>

                      </tr>
                    <?php } ?>  
                </tbody>
              </table>
            </div>

            <div class="form-group">
              <label class="col-md-2 control-label"></label>
              <div class="col-md-8">
                <a href="/recFinanDPSRecurso" class="btn btn-success" >Retorna</a>

                <a class="btn btn-primary" href="#" onclick="chamaInsereDados()">Incluir Novo Valor</a>
              </div>
            </div>

          </div>
        </div>
       </form>
      </div>
    </section>

    <script src="sendPost.js"></script>

    <script>
      function chamaInsereDados(){
         sendPost('/recFinanDPSRecursoVMRMenu', {origem:'inclusao'});         
      };  
    </script>
  </body>
</html>