<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu Consulta de Subitem de Necessidade
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/apoioSubitemConsultarMenu" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta de Subitem de Necessidade Almoxarifado</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11>Campo Obrigatório</p>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="codGrupo">Item Necessidade<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="cb_item_escolhido" name="cb_item_escolhido" class="form-control" disabled="">
                    <option value="">Selecione Botão "Carregar Item"</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeGrupo">Subitem Necessidade</label>  
                <div class="col-md-4">
                  <select required id="cb_subitem_escolhido" name="cb_subitem_escolhido" class="form-control" disabled="">
                    <option value="">Escolha Subitem</option>
                  </select>
                </div>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <button class="btn btn-primary" id="btnBuscar" type="Submit" disabled="">Buscar</button>

                  <a href="/apoioItemSubitem" class="btn btn-success" >Retorna</a>
                  
                  <a class="btn" id="btnItem"></a>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroApoio == 3) { ?>
             <small class="form-text text-danger">Item/Subitem Precisam ser escolhidos!</small>
          <?php } ?>
        </div>

      </div>
    </section>

    <script>
      <?php if ($this->view->erroApoio >= 0 ) { ?>
        $(function() {
            $('#btnItem').on("click", function () {
              $('#btnItem').hide();
          });
          // Chama a função de clique através do trigger
          $("#btnItem").trigger('click');
        })
      <?php } ?>

      $('#btnItem').click(function(e){
          //$('#btnItem').hide();
          $("#btnBuscar").removeAttr("disabled");
          $("#cb_item_escolhido").removeAttr("disabled");
          $("#cb_subitem_escolhido").removeAttr("disabled");
          $('#cb_item_escolhido').empty().append('<option>Escolha Item</option>>');
          $('#cb_subitem_escolhido').empty().append('<option>Escolha Subitem</option>');

          // Carrega Itens          
          $.getJSON('ConsultaCbDependente.php?opcao=item', function (dados){

             if (dados.length > 0){    
                var option = '<option>Escolha Item</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_item+'">'+obj.nome_item+'</option>';
                })
              }else{
                 Reset();
             }
             $('#cb_item_escolhido').html(option).show();
          })
      })

      // Carrega Subitens
      $('#cb_item_escolhido').change(function(e){
        var item = $('#cb_item_escolhido').val();
          $.getJSON('ConsultaCbDependente.php?opcao=subitem&valor='+item, 
          function (dados){ 
           
             if (dados.length > 0){    
                var option = '<option>Escolha Subitem</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_subitem+'">'+obj.nome_subitem+'</option>';
                })
             }else{
                Reset();
             }
             $('#cb_subitem_escolhido').html(option).show(); 
          })
      })

      // Resetar Selects 
      function Reset(){
          $('#cb_item_escolhido').empty().append('<option>Escolha Item</option>>');
          $('#cb_subitem_escolhido').empty().append('<option>Escolha Subitem</option>');

           <?php if ($this->view->erroApoio >= 0 ) { ?>
            $(function() {
                $('#btnItem').on("click", function () {
                  $('#btnItem').hide();
              });
              // Chama a função de clique através do trigger
              $("#btnItem").trigger('click');
            })
          <?php } ?>
      }
    </script>  
  </body>
</html>