<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Incluir Subitem
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/apoioSubitemIncluirBase" method="post" id="FormIncluir">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Inclusão de Subitem de Necessidade Almoxarifado</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="item_escolhido">Item Necessidade<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="item_escolhido" name="item_escolhido" class="form-control">
                    <?php foreach ($this->view->itens as $indice => $item) { ?>
                      <option value=<?= $item['cod_item'] ?>><?= $item['nome_item'] ?></option>
                    <?php } ?>  
                  </select>
                </div>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeSubitem">Nome Subitem</label>  
                <div class="col-md-4">
                  <input id="NomeSubitem" name="nomeSubitem" placeholder="Digite o nome do Subitem" class="form-control input-md" required="" type="text" maxlength="30" autofocus >
                </div>
              </div>
                
              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <button class="btn btn-primary" type="button" id="btnIncluir">Cadastrar</button>

                  <button id="Limpar" name="Cancelar" class="btn btn-danger" type="Reset">Limpar Campos</button>

                  <a href="/apoioItemSubitem" class="btn btn-success" >Retorna</a>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>
    
        <div class="col infoErro text-center" >
          <?php if ($this->view->erroApoio == 1) { ?>
             <small class="form-text text-danger">Inclusão realizada com Sucesso!<?php echo ' Item ('.$this->view->codItem_inserido.') - Subitem: '.$this->view->nomeSubitem_inserido ?></small>
          <?php } else if ($this->view->erroApoio == 2) { ?>
             <small class="form-text text-danger">Erro: Nome do Subitem Já cadastrado! <?php echo ' '.$this->view->nomeSubitem_inserido. ', ' ?>Verifique!</small>
          <?php } ?>
        </div>

      </div>
    </section>

    <!-- Para mostrar Alerta de Confima ou Não -->
    <script src="alertaConfirmaInclui.js"></script>
  </body>
</html>