<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Alteração de Subitem da Necessidae
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
    <!--<link rel="/stylesheet" href="bootstrap/dist/css/bootstrap.min.css">-->
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/apoioSubitemAlterarMenu" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Alteração de Subitem de Necessidade Almoxarifado</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_item_escolhido">Item Necessidade<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="cb_item_escolhido" name="cb_item_escolhido" class="form-control" disabled="">
                    <option value="">Selecione Botão "Carregar Item"</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_subitem_escolhido">Subitem Necessidade<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="cb_subitem_escolhido" name="cb_subitem_escolhido" class="form-control" disabled="">
                    <option value="">Escolha Subitem</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Alterar"></label>
                <div class="col-md-8">
                  <button class="btn btn-primary" id="btnBuscar" type="Submit" disabled="">Buscar</button>

                  <a href="/apoioItemSubitem" class="btn btn-success" >Retorna</a>
                    
                  <a class="btn" id="btnItem"></a>
                </div>
              </div>
            </div>

          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroApoio == 1) { ?>
             <small class="form-text text-danger">Alteração realizada com Sucesso!<?php echo $this->view->nomeSubitem_alterado ?></small>
          <?php } else if ($this->view->erroApoio == 3) { ?>
             <small class="form-text text-danger">Item/Subitem precisam ser escolhidos!</small>
          <?php } ?>
        </div>

      </div>
    </section>
   
    <script>
      // Para simular o clique do botão e abrir as opções de Item e Subitem
      <?php if ($this->view->erroApoio >= 0 ) { ?>
        $(function() {
            $('#btnItem').on("click", function () {
              $('#btnItem').hide();
          });
          // Chama a função de clique através do trigger
          $("#btnItem").trigger('click');
        })
      <?php } ?>

      // Comando abaixo era usado qdo tinha que se teclar no botão, o que foi eliminado pela lógica acima
      //$(document).ready(function(){

        $('#btnItem').click(function(e){
            //$('#btnItem').hide();
            $("#btnBuscar").removeAttr("disabled");
            $("#cb_item_escolhido").removeAttr("disabled");
            $("#cb_subitem_escolhido").removeAttr("disabled");
            $('#cb_item_escolhido').empty().append('<option>Escolha Item</option>>');
            $('#cb_subitem_escolhido').empty().append('<option>Escolha Subitem</option>');

            // Carrega Itens          
            $.getJSON('ConsultaCbDependente.php?opcao=item', function (dados){

               if (dados.length > 0){    
                  var option = '<option>Escolha Item</option>';
                  $.each(dados, function(i, obj){
                      option += '<option value="'+obj.cod_item+'">'+obj.nome_item+'</option>';
                  })
                }else{
                   Reset();
               }
               $('#cb_item_escolhido').html(option).show();
            })
        })

        // Carrega Subitens
        $('#cb_item_escolhido').change(function(e){
          var item = $('#cb_item_escolhido').val();
            $.getJSON('ConsultaCbDependente.php?opcao=subitem&valor='+item, 
            function (dados){ 
             
               if (dados.length > 0){    
                  var option = '<option>Escolha Subitem</option>';
                  $.each(dados, function(i, obj){
                      option += '<option value="'+obj.cod_subitem+'">'+obj.nome_subitem+'</option>';
                  })
               //}else{
               //   Reset();
               }
               $('#cb_subitem_escolhido').html(option).show(); 
            })
        })

       // Resetar Selects -->
      function Reset(){
        $('#cb_item_escolhido').empty().append('<option>Escolha Item</option>>');
        $('#cb_subitem_escolhido').empty().append('<option>Escolha Subitem</option>');

        // Para simular o clique do botão e abrir as opções de Item e Subitem
        <?php if ($this->view->erroApoio >= 0 ) { ?>
          $(function() {
              $('#btnItem').on("click", function () {
                //console.log('entrou 1.....');
                $('#btnItem').hide();
            });
            // Chama a função de clique através do trigger
            $("#btnItem").trigger('click');
          })
        <?php } ?>
      }
    </script>
  </body>
</html>