<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Alteração definitiva de Subitem de Necessidade
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/apoioSubitemAlterarBase" method="post" id="FormAltera">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Alteração de Subitem de Necessidade Almoxarifado</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório</p>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="codItem">Código Item</label>  
                <div class="col-lg-1">
                  <input id="CodItem" name="codItem"class="form-control input-md" readonly="readonly" type="text" value=<?= $this->view->dadosSubitem_escolhida['cod_item_a_alterar'] ?>>              </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeItem">Nome Item</label>  
                <div class="col-md-4">
                  <input id="NomeItem" name="nomeItem"class="form-control input-md" readonly="readonly" type="text" value="<?= $this->view->dadosSubitem_escolhida['nome_item_a_alterar'] ?>">              </div>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="codSubitem">Código Subitem</label>  
                <div class="col-lg-1">
                  <input id="CodSubitem" name="codSubitem"class="form-control input-md" readonly="readonly" type="text" value=<?= $this->view->dadosSubitem_escolhida['cod_subitem_a_alterar'] ?>>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeSubitem">Nome Subitem<h11>*</h11></label>  
                <div class="col-md-4">
                  <input autofocus id="1" name="nomeSubitem" placeholder="Digite o nome do Subitem" class="form-control input-md" required="" type="text" maxlength="30" value="<?= $this->view->dadosSubitem_escolhida['nome_subitem_a_alterar'] ?>">
                </div>
              </div>
                
              <div class="form-group">
                <label class="col-md-2 control-label" for="Alterar"></label>
                <div class="col-md-8">
                  <button class="btn btn-primary" type="button" id="btnAlterar">Alterar</button>

                  <a href="/apoioSubitemAlterar" class="btn btn-success" >Retorna</a>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>
    
        <div class="col infoErro text-center">
          <?php if ($this->view->erroApoio == 2) { ?>
             <small class="form-text text-danger">Erro: Nome do Subitem Já cadastrado! <?php echo ' '.$this->view->nomeItem_alterado. ', ' ?>Verifique!</small>
          <?php } ?>
        </div>

      </div>
    </section>

    <!-- Para mostrar Alerta de Confima ou Não -->
    <script src="alertaConfirmaAltera.js"></script>
  </body>
</html>