<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Alteração de Grupo
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">  
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/grupoAlterarMenu" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Alteração de Grupo</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="grupo_escolhido">Nome Grupo<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="grupo_escolhido" name="grupo_escolhido" class="form-control">
                    <?php foreach ($this->view->grupos as $indice => $grupo) { ?>
                      <option value=<?= $grupo['cod_grupo'] ?>><?= $grupo['nome_grupo'] ?></option>
                    <?php } ?>  
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="/grupoSubgrupo" class="btn btn-success" >Retorna</a>

                  <button class="btn btn-primary" type="Submit">Buscar</button>
                </div>
              </div>
  
            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
             <small class="form-text text-danger">Alteração realizada com Sucesso!<?php echo ' Grupo: '.$this->view->codGrupo_alterado ?></small>
          <?php } ?>
        </div>

      </div>
    </section>
  </body>
</html>