<!--  Nome Programador: Paulo Tarrago Jaques
        Data de criação: 16/10/2019
      Objetivo:  Menu com todas os voluntários vinculados ao grupo e subgrupo escolhidos
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container">
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta Vínculo Voluntário com Subgrupo</h4></div>
            <div class="panel-body">
              <div class="container">
                Grupo: <?php echo $this->view->codGrupo. ' - '. $this->view->nomeGrupo ?>
              </div>

              <?php if (!empty($this->view->codSubgrupo)) { ?>
                <div class="container">
                  Subgrupo: <?php echo $this->view->codSubgrupo. ' - '. $this->view->nomeSubgrupo ?>
                </div>
              <?php } else { ?>
                <div class="container" style="font-size: 95%; color: blue">
                  * Somente Cadastro no Grupo. Não houve cadastro em Subgrupo!
                </div>
              <?php } ?>

              <div class="table-responsive-md">
                <table class="table table-striped table-bordered table-hover">
                  <thead class="thead-light">
                  <tr>
                    <!-- Nome das Colunas -->
                    <!--<th scope="col">Sequencial</th>-->
                    <th scope="col">Código Voluntário</th>
                    <th scope="col">Nome Voluntário</th>

                    <?php if (empty($this->view->codSubgrupo)) { ?>
                      <th scope="col">Nome Subgrupo</th>
                    <?php } ?>                    

                    <th scope="col">Perfil Atuação</th>
                    <th scope="col">Data Início Vínculo</th>
                    <th scope="col">Data Término Vínculo</th>
                    <th scope="col">Situação Vínculo</th>
                  </tr>
                  </thead>
                  
                  <tbody>
                    <?php foreach ($this->view->dadosTVVG as $indice => $registro) { ?>
                      <tr style='cursor:pointer'>
                      
                        <td><?php echo $registro['cd_vlnt']; ?></td>

                        <td><a href="#" onclick="sendPost('/voluntarioConsultarMenu', {voluntario_escolhido:'<?= $registro['cd_vlnt'] ?>',dt_inc:'<?= $registro['data_inicial'] ?>', dt_fim:'<?= $registro['data_final'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rotaV:'cvvgs'});"><?php echo $registro['nm_vlnt']; ?></a>
                        </td>

                        <?php if (empty($this->view->codSubgrupo)) { ?>
                          <?php if ($registro['nm_sbgrp'] == '*') { ?>
                            <td style="font-size: 120%; color: blue" class="text-center"><?php echo $registro['nm_sbgrp']; ?></td>
                          <?php } else {?>                    
                            <td><?php echo $registro['nm_sbgrp']; ?></td>                            
                          <?php } ?>                    
                        <?php } ?>                    

                        <td><?php echo $registro['perfil_atuacao']; ?></td>
                        
                        <td><?php echo $registro['data_inicio_vinculo']; ?></td>
                        
                        <td><?php echo $registro['data_fim_vinculo']; ?></td>
                        
                        <?php if ($registro['situacao_vinculo'] == 'Encerrado') { ?>                        
                          <td style="color: red"><?php echo $registro['situacao_vinculo']; ?></td>
                        <?php } else {?>                    
                          <td><?php echo $registro['situacao_vinculo']; ?></td>                        
                        <?php } ?>                    
                      
                      </tr>

                    <?php } ?>  
                  </tbody>
                </table>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-8">
                  <a href="/subgrupoConsultarVinculoVoluntario" class="btn btn-success" >Retorna</a>
                  
                  <a class="btn" id="btnGrupo"></a>
                </div>
              </div>

            </div>
          </div>
        </form>


      </div>
    </section>
    
    <!-- Para Possibilitar $_POST -->
    <script src="sendPost.js"></script>
  </body>
</html>