<!--  Nome Programador: Paulo Tarrago Jaques
        Data de criação: 04/07/2019
      Objetivo:  Menu com todas as famílias que estão sendo atendidas pelo grupo e subgrupo escolhidos
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container">
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta Vínculo Família com Subgrupo</h4></div>
            <div class="panel-body">
              <div class="container">
                Grupo: <?php echo $this->view->codGrupo. ' - '. $this->view->nomeGrupo ?>
              </div>
              <div class="container">
                Subgrupo: <?php echo $this->view->codSubgrupo. ' - '. $this->view->nomeSubgrupo ?>
              </div>

              <div class="table-responsive-md">
                <table class="table table-striped table-bordered table-hover">
                  <thead class="thead-light">
                  <tr>
                    <!-- Nome das Colunas -->
                    <th scope="col">Sequencial</th>
                    <th scope="col">Código Família</th>
                    <th scope="col">Nome Família</th>
                    <th scope="col">Data Início Vínculo</th>
                    <th scope="col">Data Término Vínculo</th>
                    <th scope="col">Situação Vínculo</th>
                    <th scope="col">Situação Família</th>
                  </tr>
                  </thead>
                  
                  <tbody>
                    <?php foreach ($this->view->dadosTVFS as $indice => $registro) { ?>
                      <tr style='cursor:pointer'>
                        <!-- Função Javascript que remete $_POST ao invés de $_GET -->
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', dt_inc:'<?= $registro['dt_inc'] ?>', dt_fim:'<?= $registro['dt_fim'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['sequencial']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', dt_inc:'<?= $registro['dt_inc'] ?>', dt_fim:'<?= $registro['dt_fim'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['codigo_familia']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', dt_inc:'<?= $registro['dt_inc'] ?>', dt_fim:'<?= $registro['dt_fim'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['nome_familia']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', dt_inc:'<?= $registro['dt_inc'] ?>', dt_fim:'<?= $registro['dt_fim'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['data_inicio_vinculo']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', dt_inc:'<?= $registro['dt_inc'] ?>', dt_fim:'<?= $registro['dt_fim'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['data_fim_vinculo']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', dt_inc:'<?= $registro['dt_inc'] ?>', dt_fim:'<?= $registro['dt_fim'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['situacao_vinculo']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', dt_inc:'<?= $registro['dt_inc'] ?>', dt_fim:'<?= $registro['dt_fim'] ?>', cb_grupo_escolhido:'<?= $registro['cb_grupo_escolhido'] ?>', cb_subgrupo_escolhido:'<?= $registro['cb_subgrupo_escolhido'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['cd_est_situ_fml']; ?></a></td>
                      
                      </tr>

                    <?php } ?>  
                  </tbody>
                </table>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-8">
                  <a href="/subgrupoConsultarVinculoFamilia" class="btn btn-success" >Retorna</a>
                  
                  <a class="btn" id="btnGrupo"></a>
                </div>
              </div>

            </div>
          </div>
        </form>


      </div>
    </section>
    
    <!-- Para Possibilitar $_POST -->
    <script src="sendPost.js"></script>
  </body>
</html>