<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Escolha de Subgrupo para Consulta
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/subgrupoConsultarMenu" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta de Subgrupo</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_grupo_escolhido">Grupo<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="cb_grupo_escolhido" name="cb_grupo_escolhido" class="form-control" disabled="">
                    <option value="">Escolha Grupo</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeGrupo">Subgrupo<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="cb_subgrupo_escolhido" name="cb_subgrupo_escolhido" class="form-control" disabled="">
                    <option value="">Escolha Subgrupo</option>
                  </select>
                </div>
              </div>
               
              <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-8">
                  <button class="btn btn-primary" id="btnBuscar" type="Submit" disabled="">Buscar</button>

                  <a href="/grupoSubgrupo" class="btn btn-success" >Retorna</a>
                  
                  <a class="btn" id="btnGrupo"></a>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 3) { ?>
             <small class="form-text text-danger">Grupo/Subgrupo precisam ser escolhidos!</small>
          <?php } ?>
        </div>

      </div>
    </section>

    <script>
      // Para simular o clique do botão e abrir as opções de Grupo e Subgrupo
      <?php if ($this->view->erroValidacao >= 0 ) { ?>
        $(function() {
            $('#btnGrupo').on("click", function () {
              $('#btnGrupo').hide();
          });
          // Chama a função de clique através do trigger
          $("#btnGrupo").trigger('click');
        })
      <?php } ?>

      $('#btnGrupo').click(function(e){
          $("#btnBuscar").removeAttr("disabled");
          $("#cb_grupo_escolhido").removeAttr("disabled");
          $("#cb_subgrupo_escolhido").removeAttr("disabled");
          $('#cb_grupo_escolhido').empty().append('<option>Escolha Grupo</option>>');
          $('#cb_subgrupo_escolhido').empty().append('<option>Escolha Subgrupo</option>');

          // Carrega Grupos          
          $.getJSON('ConsultaCbDependente.php?opcao=grupo', function (dados){

             if (dados.length > 0){    
                var option = '<option>Escolha Grupo</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_grupo+'">'+obj.nome_grupo+'</option>';
                })
              }else{
                 Reset();
             }
             $('#cb_grupo_escolhido').html(option).show();
          })
      })

      // Carrega Subgrupos
      $('#cb_grupo_escolhido').change(function(e){
        var grupo = $('#cb_grupo_escolhido').val();
          $.getJSON('ConsultaCbDependente.php?opcao=subgrupo2&valor='+grupo, 
          function (dados){ 
           
             if (dados.length > 0){    
                var option = '<option>Escolha Subgrupo</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_subgrupo+'">'+obj.nome_subgrupo+'</option>';
                })
             }else{
                Reset();
             }
             $('#cb_subgrupo_escolhido').html(option).show(); 
          })
      })

      // Resetar Selects -->
      function Reset(){
        $('#cb_grupo_escolhido').empty().append('<option>Escolha Grupo</option>>');
        $('#cb_subgrupo_escolhido').empty().append('<option>Escolha Subgrupo</option>');

        <?php if ($this->view->erroValidacao >= 0 ) { ?>
          $(function() {
              $('#btnGrupo').on("click", function () {
                $('#btnGrupo').hide();
            });
            // Chama a função de clique através do trigger
            $("#btnGrupo").trigger('click');
          })
        <?php } ?>
      }
    </script>
  </body>
</html>