<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de escolha de família para poder incluir integrante
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/familiaCadastroIncluirIntegranteMenu" method="post">
          <div class="panel panel-primary"> 
            <div class="panel-heading"><h4>Incluir Integrante de Família</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="familia_escolhida">Família<h11>*</h11></label>  
                <div class="col-md-4">
                  <select required id="familia_escolhida" name="familia_escolhida" class="form-control">
                    <?php foreach ($this->view->familias as $indice => $familia) { ?>
                      <option value=<?= $familia['cd_fmlID'] ?>><?= $familia['nm_grp_fmlr'] ?></option>
                    <?php } ?>  
                  </select>
                </div>
              </div>
                 
              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="/familiaCadastro" class="btn btn-success" >Retorna</a>

                  <button class="btn btn-primary" type="Submit">Buscar</button>
                </div>
              </div>
			      
            </div>
          </div>
        </form>
        </fieldset>
      </div>
    </section>
  </body>
</html>