<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu Intermediário com informações das famílias para pesquisa
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" id="bootstrap-css">

    <style type="text/css">
      /* Link acessado e não acessado */
      a:link, a:visited {
        color: #3E8CCE;
      }

      /* qdo o mouse passa por cima do Link */  
      a:hover {
        color: #fff;
        background-color: #3E8CCE;
        text-decoration: none;
      }
    </style>
  </head>

  <body>
    <section class="caixa">
      <div class="container">
       <form class="form-horizontal" action="" method="post" id="FormTabela">
        <div class="panel panel-primary">
          <div class="panel-heading"><h4>Consulta de Família</h4></div>
          <div class="panel-body">
            <div class="table-responsive-md">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                  <!-- Nome das Colunas -->
                  <th scope="col">Código Família</th>
                  <th scope="col">Nome Família</th>
                  <th scope="col">Dt Início Acomp</th>
                  <th scope="col">Dt Fim Acomp</th>
                  <th scope="col">Situação Família</th>
                  <th scope="col">Informações Família</th> 
                </tr>
                </thead>
                
                <tbody>
                    <?php foreach ($this->view->familia as $indice => $familia) { ?>
                      <tr style='cursor:pointer'>

                        <!-- Passa por $_GET o código da Família para mostrar dados na consulta -->
                        <td class="text-center"><?php echo $familia['cd_fml']; ?></td>

                        <td><?php echo $familia['nm_grp_fmlr']; ?></td>

                        <td><?php echo $familia['dt_inc_acomp']; ?></td>

                        <td><?php echo $familia['dt_enct_acomp']; ?></td>

                        <td><?php echo $familia['cd_est_situ_fml']; ?></td>
                                              
                        <!-- Função Javascript que remete $_POST ao invés de $_GET -->
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $familia['cd_fml'] ?>', cpf_pre:'<?= $familia['cpf_pre'] ?>', nm_astd_pre:'<?= $familia['nm_astd_pre'] ?>', rota:'<?= $familia['rota'] ?>'});">Detalha Informações</a></td>
                      </tr>
                    <?php } ?>  
                </tbody>
              </table>

              <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-8">
                  <a style="color: white" href="/familiaCadastroConsultar" class="btn btn-success" >Retorna</a>
                </div>
              </div>

            </div>
          </div>
        </div>
       </form>
      </div>
    </section>
      
    <script src="sendPost.js"></script>
  </body>
</html>