<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu Principal de funcionalidades para cadastro de família
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary"> 
            <div class="panel-heading"><h4>Família e Integrantes</h4></div>
            <div class="panel-body">

              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <label class="col-md-2 control-label colorLabelTituloList">Família</label>  
                  </ul>
                </div>

                <div class="col-md-2">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaCadastroPreIncluir">Incluir</a>
                  </ul>
                </div>

                <div class="col-md-2">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaCadastroAlterar">Alterar</a>
                  </ul>
                </div>

                <div class="col-md-2">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaCadastroConsultar">Consultar</a>
                  </ul>
                </div>
              </div>
        
              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <label class="col-md-12 control-label colorLabelTituloList">Integrante Família</label>  
                  </ul>
                </div>

                <div class="col-md-2">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaCadastroIncluirIntegrante">Incluir</a>
                  </ul>
                </div>

                <div class="col-md-2">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaCadastroAlterarIntegrante">Alterar</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaCadastroEncerrarIntegrante">Encerrar Vínculo Integrante na Família</a>
                  </ul>
                </div>

                <div class="col-md-2">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/familiaCadastroConsultarIntegrante">Consultar</a>
                  </ul>
                </div>
              </div>

              <div class="form-group">
                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <label class="col-md-12 control-label colorLabelTituloList">Vínculo Família Grupo/Subgrupo</label>  
                  </ul>
                </div>
                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/subgrupoVincularFamilia">Vincular Família a Subgrupo</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/subgrupoDesvincularFamilia">Encerrar Vínculo de Família com Subgrupo</a>
                  </ul>
                </div>

                <div class="col-md-4">
                  <ul class="list-group text-center">
                      <a class="list-group-item list-group-item-info" href="/subgrupoConsultarVinculoFamilia">Consultar Vínculo Família e Subgrupo</a>
                  </ul>
                </div>

                <div class="col-md-5">
                  <ul class="list-group text-center">
                      <!-- Para mostrar a quantidade de famílias sem grupo na tela inicial -->
                      <a class="list-group-item list-group-item-info" href="/subgrupoConsultarSemVinculoFamilia">Consultar Famílias sem vínculo com Subgrupo<span class="badge badge-warning"><?= $this->view->qtdFamiliasSemVinculo ?></span></a>
                  </ul>
                </div>

                <div class="col-md-12 d-flex">
                  <ul class="list-group">
                      <a class="list-group-item active bg-success" href="/menuPrincipal">Retorna</a>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
           <small class="form-text text-danger">Erro: Voluntário sem nível de acesso apropriado!</small>
           <small class="form-text text-danger"><?php echo "Nível Requerido: ".$this->view->nivelRequerido." - Seu Nível Atual: ".$this->view->nivelLogado ?></small>
          
          <?php } else if ($this->view->erroValidacao == 2) { ?>        
             <small class="form-text text-danger">Inclusão realizada com Sucesso!<?php echo ' Família: '.$this->view->codigoInclusao. ' - '.$this->view->nomeInclusao ?></small>

          <?php } else if ($this->view->erroValidacao == 9) { ?>
             <small class="form-text text-danger">Erro: <?php echo ' '.$this->view->erroException ?>Verifique!</small>


          <?php } ?>
        </div>

      </div>
    </section>
  </body>
</html>