<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Vinculação de Família a Grupo e Subgrupo
-->
<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/subgrupoVincularFamiliaBase" method="post" id="FormVincula">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Vincular Família a Grupo/Subgrupo</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11> Campo Obrigatório </p>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_grupo_escolhido">Grupo<h11>*</h11></label>  
                <div class="col-lg-4">
                  <select required id="cb_grupo_escolhido" name="cb_grupo_escolhido" class="form-control">
                    <option value="">Escolha Grupo</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_subgrupo_escolhido">Subgrupo<h11>*</h11></label>  
                <div class="col-lg-4">
                  <select required id="cb_subgrupo_escolhido" name="cb_subgrupo_escolhido" class="form-control">
                    <option value="">Escolha Subgrupo</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_familia_escolhida">Família<h11>*</h11></label>  
                <div class="col-lg-4">
                  <select required id="cb_Familia_escolhida" name="cb_familia_escolhida" class="form-control">

                    <?php function selected( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <!-- Para simular "placeholder" no combobox -->
                    <option value="">Escolha Família</option> 

                    <?php foreach ($this->view->familias as $indice => $familia) { ?>

                      <option value="<?= $familia['cd_fmlID'] ?>"<?php echo selected($familia['cd_fmlID'], $this->view->vinculo['cb_familia_escolhida']); ?>><?= $familia['nm_grp_fmlr'] ?></option>

                    <?php } ?>  
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Vincular"></label>
                <div class="col-md-8">
                  <button class="btn btn-primary" id="btnBuscar" type="button" disabled="">Vincular</button>

                  <a href="/familiaCadastro" class="btn btn-success" >Retorna</a>
                  
                  <a class="btn" id="btnGrupo"></a>
                </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroValidacao == 1) { ?>
              <small class="form-text text-danger">Vinculo Realizado com Sucesso!</small>
              <small class="form-text text-danger">Grupo:  <?php echo ' '.$this->view->grupoTratado ?> </small>
              <small class="form-text text-danger">Subgrupo:  <?php echo ' '.$this->view->subgrupoTratado ?> </small>
              <small class="form-text text-danger">Família:  <?php echo ' '.$this->view->familiaTratada ?> </small>
          <?php } else if ($this->view->erroValidacao == 2) { ?>
              <small class="form-text text-danger">Grupo e Subgrupo precisam ser escolhidos!</small>
          <?php } else if ($this->view->erroValidacao == 3) { ?>
              <small class="form-text text-danger">Vinculo já existente para esta Família!</small>
              <small class="form-text text-danger">Grupo:  <?php echo ' '.$this->view->grupoTratado ?> </small>
              <small class="form-text text-danger">Subgrupo:  <?php echo ' '.$this->view->subgrupoTratado ?> </small>
              <small class="form-text text-danger">Família:  <?php echo ' '.$this->view->familiaTratada ?> </small>

          <?php } else if ($this->view->erroValidacao == 4) { ?>
              <small class="form-text text-danger">Voluntário Não está Vinculado ao Grupo e Subgrupo!</small>
              <small class="form-text text-danger">Grupo:  <?php echo ' '.$this->view->grupoTratado ?> </small>
              <small class="form-text text-danger">Subgrupo:  <?php echo ' '.$this->view->subgrupoTratado ?> </small>
          
          <?php } else if ($this->view->erroValidacao == 5) { ?>
             <small class="form-text text-danger">Voluntário sem nível de atuação apropriado!</small>
             <small class="form-text text-danger"><?php echo "Atuação Requerida: ".$this->view->atuacaoRequerida." - Sua Atuação Atual: ".$this->view->atuacaoLogado ?></small>
              <small class="form-text text-danger">Grupo:  <?php echo ' '.$this->view->grupoTratado ?> </small>
              <small class="form-text text-danger">Subgrupo:  <?php echo ' '.$this->view->subgrupoTratado ?> </small>
          <?php } ?>
        </div>

      </div>
    </section>

    <script>
      // Para simular o clique do botão e abrir as opções de Grupo e Subgrupo
      <?php if ($this->view->erroValidacao >= 0 ) { ?>
        $(function() {
            $('#btnGrupo').on("click", function () {
              $('#btnGrupo').hide();
          });
          // Chama a função de clique através do trigger
          $("#btnGrupo").trigger('click');
        })
      <?php } ?>

      $('#btnGrupo').click(function(e){
          $("#btnBuscar").removeAttr("disabled");
          $("#cb_grupo_escolhido").removeAttr("disabled");
          $("#cb_subgrupo_escolhido").removeAttr("disabled");
          $('#cb_grupo_escolhido').empty().append('<option>Escolha Grupo</option>>');
          $('#cb_subgrupo_escolhido').empty().append('<option>Escolha Subgrupo</option>');

          // Carrega Grupos          
          $.getJSON('ConsultaCbDependente.php?opcao=grupo', function (dados){

             if (dados.length > 0){    
                var option = '<option>Escolha Grupo</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_grupo+'">'+obj.nome_grupo+'</option>';
                })
              }else{
                 Reset();
             }
             $('#cb_grupo_escolhido').html(option).show();
          })
      })

      // Carrega Subgrupos
      $('#cb_grupo_escolhido').change(function(e){
        var grupo = $('#cb_grupo_escolhido').val();
          $.getJSON('ConsultaCbDependente.php?opcao=subgrupo&valor='+grupo, 
          function (dados){ 
           
             if (dados.length > 0){    
                var option = '<option>Escolha Subgrupo</option>';
                $.each(dados, function(i, obj){
                    option += '<option value="'+obj.cod_subgrupo+'">'+obj.nome_subgrupo+'</option>';
                })
              }else{
                Reset(); 
             }

             $('#cb_subgrupo_escolhido').html(option).show(); 
          })
      })

      // Resetar Selects //
      function Reset(){
        $('#cb_grupo_escolhido').empty().append('<option>Escolha Grupo</option>>');
        $('#cb_subgrupo_escolhido').empty().append('<option>Escolha Subgrupo</option>');

        <?php if ($this->view->erroValidacao >= 0 ) { ?>
          $(function() {
              $('#btnGrupo').on("click", function () {
                $('#btnGrupo').hide();
            });
            // Chama a função de clique através do trigger
            $("#btnGrupo").trigger('click');
          })
        <?php } ?>
      }
    </script>  

    <!-- Para mostrar Alerta de Confirma ou Não -->
    <script src="alertaConfirmaVincula.js"></script>
  </body>
</html>