<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu com relação das famílias que ainda estão sem definição de grupo e subgrupo
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">    
  </head>

  <body>
    <section class="caixa">
      <div class="container">
        <form class="form-horizontal" action="" method="post" id="FormConsulta">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta Famílias sem Vínculo com Subgrupo</h4></div>
            <div class="panel-body">
              <div class="table-responsive-md">
                <table class="table table-striped table-bordered table-hover">
                  <thead class="thead-light">
                  <tr>
                    <!-- Nome das Colunas -->
                    <th scope="col">Código Família</th>
                    <th scope="col">Nome Família</th>
                    <th scope="col">Responsável pela Família</th>
                    <th scope="col">Data Cadastro</th>
                    <th scope="col">Região Administrativa</th>
                    <th scope="col">UF</th>
                  </tr>
                  </thead>

                  <tbody>
                    <?php foreach ($this->view->dadosSemVinculoFml as $indice => $registro) { ?>
                      <tr>
                        <!-- Função Javascript que remete $_POST ao invés de $_GET -->
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['codigo_familia']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['nome_familia']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['nome_assistido_principal']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['data_cadastro']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['regiao_administrativa']; ?></a></td>
                        
                        <td><a href="#" onclick="sendPost('/familiaCadastroConsultarMenu', {familia_escolhida:'<?= $registro['codigo_familia'] ?>', rota:'<?= $registro['rota'] ?>'});"><?php echo $registro['uf_regiao_administrativa']; ?></a></td>
                      </tr>
                    <?php } ?>  
                  </tbody>
                </table>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-8">
                  <a href="/grupoSubgrupo" class="btn btn-success" >Retorna</a>
                  
                  <a class="btn" id="btnGrupo"></a>
                </div>
              </div>
          
            </div>
          </div>
        </form>
      </div>
    </section>

    <!-- Para Possibilitar $_POST -->
    <script src="sendPost.js"></script>
  </body>
</html>