<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Consulta de Item da Necessidade
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/apoioItemConsultarBase" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta de Item de Suprimento</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-md-2 control-label" for="codItem">Código Item</label>  
                <div class="col-lg-1">
                  <input id="CodItem" name="codItem"class="form-control input-md" readonly="readonly" type="text" value=<?= $this->view->dadosItem_escolhida['cd_item_a_consultar'] ?>>              </div>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeItem">Nome Item</label>  
                <div class="col-md-4">
                  <input id="Nome" name="nomeItem" placeholder="Digite o nome do Item" readonly="readonly" class="form-control input-md" required="" type="text" value="<?= $this->view->dadosItem_escolhida['nome_item_a_consultar'] ?>">              
                </div>
              </div>
                
              <div class="form-group">
                <label class="col-md-2 control-label" for="descricaoSubgrupo">Evento Necessidade</label>  
                <div class="col-md-4">
                  <select required id="Evento" name="evento" class="form-control"  disabled="disabled"> 
                    <?php function selected( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <option value="1"<?php echo selected('1', $this->view->dadosItem_escolhida['cd_evento_a_consultar']); ?>>Necessidade para Próxima Visita</option>
                    <option value="2"<?php echo selected('2', $this->view->dadosItem_escolhida['cd_evento_a_consultar']); ?>>Necessidade Eventual</option>
                    <option value="3"<?php echo selected('3', $this->view->dadosItem_escolhida['cd_evento_a_consultar']); ?>>Necessidade para Data Comemorativa</option>
                  </select>

                  <input type="hidden" name="evento" value=<?= $this->view->dadosItem_escolhida['cd_evento_a_consultar'] ?>> 
                </div>
  			      </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="/apoioItemConsultar" class="btn btn-success" >Retorna</a>              </div>
              </div>
        
            </div>
          </div>
        </fieldset>
        </form>
      </div>
    </section>    
  </body>
</html>