<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Alteração de Item de Necessidade
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/apoioItemAlterarMenu" method="post">
          <div class="panel panel-primary"> <!-- bg-primary "> -->
            <div class="panel-heading"><h4>Alteração de Item de Suprimento</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-md-2 control-label" for="codGrupo">Item Suprimento</label>  
                <div class="col-md-4">
                  <select required id="item_escolhido" name="item_escolhido" class="form-control">
                    <?php foreach ($this->view->itens as $indice => $item) { ?>
                      <option value=<?= $item['cod_item'] ?>><?= $item['nome_item'] ?></option>
                    <?php } ?>  
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="/apoioItemSubitem" class="btn btn-success" >Retorna</a>

                  <button class="btn btn-primary" type="Submit">Buscar</button>
                </div>
              </div>

            </div>
          </form>
          </fieldset>

        <div class="col infoErro text-center" >
          <?php if ($this->view->erroApoio == 1) { ?>
             <small class="form-text text-danger">Alteração realizada com Sucesso!<?php echo ' '.$this->view->nomeItem_alterado.' ('.
             $this->view->evento_alterado.')' ?></small>
          <?php } ?>
        </div>

      </div>
    </section>
  </body>
</html>