<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Consulta de Item de Necessidade
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="/apoioItemConsultarMenu" method="post">
          <div class="panel panel-primary"> 
            <div class="panel-heading"><h4>Consulta de Item de Suprimento</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-md-2 control-label" for="codGrupo">Item Suprimento</label>  
                <div class="col-md-4">
                  <select required id="item_escolhido" name="item_escolhido" class="form-control">
                    <?php foreach ($this->view->itens as $indice => $item) { ?>
                      <option value=<?= $item['cod_item'] ?>><?= $item['nome_item'] ?></option>
                    <?php } ?>  
                  </select>
                </div>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="/apoioItemSubitem" class="btn btn-success" >Retorna</a>

                  <button class="btn btn-primary" type="Submit">Buscar</button>
                </div>
              </div>
            
            </div>
          </div>
        </form>
        </fieldset>
      </div>
    </section>
  </body>
</html>