<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 04/07/2019
      Objetivo:  Menu de Consulta de Subitem de Necessidade
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">   
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>    
        <form class="form-horizontal" action="" method="post">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Consulta de Subitem de Suprimento</h4></div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-md-2 control-label" for="codItem">Código Item</label>  
                <div class="col-lg-1">
                  <input id="CodItem" name="codItem"class="form-control input-md" readonly="readonly" type="text" value=<?= $this->view->dadosSubitem_escolhida['cod_item_a_alterar'] ?>>              </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeItem">Nome Item</label>  
                <div class="col-md-4">
                  <input id="NomeItem" name="nomeItem"class="form-control input-md" readonly="readonly" type="text" value="<?= $this->view->dadosSubitem_escolhida['nome_item_a_alterar'] ?>">              </div>
              </div>
                  
              <div class="form-group">
                <label class="col-md-2 control-label" for="codSubitem">Código Subitem</label>  
                <div class="col-lg-1">
                  <input id="CodSubitem" name="codSubitem"class="form-control input-md" readonly="readonly" type="text" value=<?= $this->view->dadosSubitem_escolhida['cod_subitem_a_alterar'] ?>>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="nomeSubitem">Nome Subitem</label>  
                <div class="col-md-4">
                  <input id="Nome" name="nomeSubitem" placeholder="Digite o nome do Subitem" class="form-control input-md" readonly="readonly" required="" type="text" value="<?= $this->view->dadosSubitem_escolhida['nome_subitem_a_alterar'] ?>">              
                </div>
              </div>
                
              <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-8">
                  <a href="/apoioSubitemConsultar" class="btn btn-success" >Retorna</a>              </div>
              </div>

            </div>
          </div>
        </form>
        </fieldset>
      </div>
    </section>
  </body>
</html>