<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 03/07/2019
      Objetivo:  Menu Principal do sistema
-->
  
<html lang="pt-br">
  <!--<body style="margin-bottom: 200px width: 600 px; margin:  0 auto;">-->
  <body>
    <section class="caixa">
      <div class="container-fluid h-100">
        <nav class="navbar navbar-expand-sm navbar-dark infoMenuTelaInicial">
          <a href="" class="navbar-brand info_voluntario">
          	<?= $this->view->info_usuario['nm_vlnt'] ?>
          </a>

          <!-- Menu Hamburguer -->
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navegacao3">
              <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Navegação -->
          <div class="collapse navbar-collapse infoMenus" id="navegacao3">
            <ul class="navbar-nav ml-auto">
     	        <li class="nav-item dropdown">
                <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Cadastro</a>
                <div class="dropdown-menu infoPopUp">
                    <a href="/voluntarioSenha" class="dropdown-item">Nova Senha</a>
                    <!-- Função Javascript que remete $_POST -->
                    <a class="dropdown-item" href="#" onclick="sendPost('/voluntarioAlterarMenu', {voluntario_escolhido:'<?= $_SESSION['id'] ?>', quemChamou:'cadastro'});">Alterar Dados Cadastrais</a>
                </div>
              </li>

     	        <li class="nav-item dropdown">
                <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Apoio</a>

                <div class="dropdown-menu infoPopUp">
	                <a href="/apoioRA" class="dropdown-item">Região Administrativa</a>
                  <a href="/apoioItemSubitem" class="dropdown-item">Item e SubItem Necessidades - Almoxarifado</a>
                </div>
              </li>

              <li class="nav-item">
                  <a href="/grupoSubgrupo" class="nav-link">Grupo/Subgrupo</a>
              </li>

              <li class="nav-item">
                  <a href="/voluntario" class="nav-link">Voluntário</a>
              </li>

     	        <li class="nav-item dropdown">
                <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Família</a>
                <div class="dropdown-menu infoPopUp">
	                <a href="/familiaCadastro" class="dropdown-item">Cadastro</a>
	                <a href="/familiaAcompanhamento" class="dropdown-item">Acompanhamentos</a>
                  <a href="/familiaNecessidade" class="dropdown-item">Necessidades</a>
                </div>
              </li>

              <li class="nav-item">
                <a href="#" class="nav-link">Suprimento</a>
              </li>

              <li class="nav-item">
                <a href="#" class="nav-link">Financeiro</a>
              </li>

              <li class="nav-item">
                <a href="#" class="nav-link">Info Gerenciais</a>
              </li>
                  
              <li class="nav-item">
                <a href="/sair" class="nav-link">Sair</a>
              </li>
            </ul>
          </div>
        </nav>   
      </div>       
    </section> 

    <section class="caixa">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <img src="img/Logotipo-CEB3.png" class="img-fluid">
          </div>

          <div class="col-md-6 d-flex">
            <div class="align-self-center">
              <h2>Avisos</h2>
              <p>
                Servirá para mostrar avisos importantes! (Fazer com tweets)
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    </div>

    <script>
      /*Script pego em "http://blog.rdtecnologia.com.br/php/passando-dados-via-post-em-javascript/" 
         simula $_POST com <a href */       
      if(!window.sendPost){
          window.sendPost = function(url, obj){
              //Define o formulário
              var myForm = document.createElement("form");
              myForm.action = url;
              myForm.method = "post";

            for(var key in obj) {
               var input = document.createElement("input");
               //input.type = "text";
               input.type = "hidden";
               input.value = obj[key];
               input.name = key;
               myForm.appendChild(input);     
            }
            //Adiciona o form ao corpo do documento
            document.body.appendChild(myForm);
            //Envia o formulário
            myForm.submit();
          };
      }  
    </script>    
  </body>
</html>

