<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 29/0+/2019
      Objetivo:  Menu de Inclusão de dados de Necessidade de Próxima Visita para Famílias
-->

<html lang="pt-br">
  <head>
    <!-- Para mostrar os campos na mesma linha - não pode ficar em "layout.pthml" pois dava conflito -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"  id="bootstrap-css">
  </head>

  <body>
    <section class="caixa">
      <div class="container"> 
        <fieldset>                             
        <form class="form-horizontal" action="/fNIncluirNecesProxVisitaBase" method="post" id="FormIncluir">
          <div class="panel panel-primary">
            <div class="panel-heading"><h4>Inclusão Item Necessidade de Família - Próxima Visita</h4></div>
            <div class="panel-body">
              <div class="col-md-11 control-label">
                <p class="help-block infoCampoObrigatorioFormulario"><h11>*</h11>Campo Obrigatório </p>
              </div>

              <div class="col-md-12 control-label text-center" >
                <?php if ($this->view->erroValidacao == 1) { ?>
                  <p class="form-text" style="background-color: #69C8E0; color: white; font-size: 100%">Inclusão realizada com sucesso!
                  <?php echo ' [Item: '.$this->view->codItem. ' - '.$this->view->nomeItem.' || ' ?>
                  <?php echo ' Subitem: '.$this->view->codSubitem.' - '.$this->view->nomeSubitem.']' ?></p>

                <?php } else if ($this->view->erroValidacao == 2) { ?>
                  <p class="form-text" style="background-color: red; color: white; font-size: 100%">Erro: Item e Subitem precisam ser escolhidos!</p>

                <?php } else if ($this->view->erroValidacao == 3) { ?>
                  <p class="form-text" style="background-color: red; color: white; font-size: 100%">Erro: Item e Subitem Já cadastrados para esta data!
                  <?php echo ' [Item: '.$this->view->codItem. ' - '.$this->view->nomeItem.' || ' ?>
                  <?php echo ' Subitem: '.$this->view->codSubitem.' - '.$this->view->nomeSubitem.']' ?></p>

                <?php } else if ($this->view->erroValidacao == 6) { ?>
                  <p class="form-text" style="background-color: red; color: white; font-size: 100%">Erro: Descrição do item sem preenchimento!
                  <?php echo ' [Item: '.$this->view->codItem. ' - '.$this->view->nomeItem.' || ' ?>
                  <?php echo ' Subitem: '.$this->view->codSubitem.' - '.$this->view->nomeSubitem.']' ?></p>

                <?php } else if ($this->view->erroValidacao == 0) { ?>
                  <p class="form-text text-danger">&nbsp</p>
                <?php } ?>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cd_grp">Grupo</label>  
                <div class="col-lg-1">
                  <input id="cd_grp" name="cd_grp" class="form-control input-md" readonly="" type="text" maxlength="6" value="<?= $this->view->dadosNecessidade['cd_grp'] ?>">
                </div>

                <div class="col-lg-5">
                  <input id="nm_grp" name="nm_grp" class="form-control input-md" readonly="" type="text" maxlength="100" value="<?= $this->view->dadosNecessidade['nm_grp'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cd_sbgrp">Subgrupo</label>  
                <div class="col-lg-1">
                  <input id="cd_sbgrp" name="cd_sbgrp" class="form-control input-md" readonly="" type="text" maxlength="6" value="<?= $this->view->dadosNecessidade['cd_sbgrp'] ?>">
                </div>

                <div class="col-lg-5">
                  <input id="nm_sbgrp" name="nm_sbgrp" class="form-control input-md" readonly="" type="text" maxlength="100" value="<?= $this->view->dadosNecessidade['nm_sbgrp'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cd_fml">Família</label>  
                <div class="col-lg-1">
                  <input id="cd_fml" name="cd_fml" class="form-control input-md" readonly="" type="text" maxlength="6" value="<?= $this->view->dadosNecessidade['cd_fml'] ?>">
                </div>

                <div class="col-lg-5">
                  <input id="nm_grp_fmlr" name="nm_grp_fmlr" class="form-control input-md" readonly="" type="text" maxlength="100" value="<?= $this->view->dadosNecessidade['nm_grp_fmlr'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="dt_proxima_visita">Data Próxima Visita</label>  
                <div class="col-lg-2">
                  <input id="dt_proxima_visita" readonly="" name="dt_proxima_visita"class="form-control input-md" type="text" value="<?= $this->view->dadosNecessidade['dt_proxima_visita'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_item_escolhido">Item<h11>*</h11></label>  
                <div class="col-lg-4">
                  <select required id="cb_item_escolhido" name="cb_item_escolhido" class="form-control">
                    <option value="">Escolha Item</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="cb_subitem_escolhido">Subitem<h11>*</h11></label>  
                <div class="col-lg-4">
                  <select required id="cb_subitem_escolhido" name="cb_subitem_escolhido" class="form-control">
                    <option value="">Escolha Subitem</option>
                  </select>
                </div>
              </div>

              <div class="form-group">    
                <label class="col-md-2 control-label" for="cd_setor_resp">Setor Responsável Atendimento<h11>*</h11></label>
                <div class="col-lg-3">
                  <select id="cd_setor_resp" name="cd_setor_resp" class="form-control">
                    
                    <?php function selected2( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <option value="1"<?php echo selected2('1', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Almoxarifado</option>
                    
                    <option value="2"<?php echo selected2('2', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Grupo/Subgrupo</option>
                    
                    <option value="3"<?php echo selected2('3', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Setor Orientação Profissional</option>
                    
                    <option value="4"<?php echo selected2('4', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Biblioteca Canguru</option>
                    
                    <option value="5"<?php echo selected2('5', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Biblioteca Canguru - Contadores de História</option>

                    <option value="6"<?php echo selected2('6', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Grupo de Desobsessão Auta de Souza</option>

                    <option value="7"<?php echo selected2('7', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Implantação do Evangelho no Lar</option>

                    <option value="8"<?php echo selected2('8', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Parcerias Médicas</option>

                    <option value="9"<?php echo selected2('9', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Grupo de Apoio e Atendimento na sede da Comunhão</option>

                    <option value="10"<?php echo selected2('10', $this->view->dadosNecessidade['cd_setor_resp']); ?>>Direção da Comunhão</option>

                  </select>
                </div>
              </div>
              
              <div class="form-group">
                <label class="col-md-2 control-label" for="obs_sobre_item">Observação</label>
                <div class="col-lg-9">
                  <input id="obs_sobre_item" name="obs_sobre_item" placeholder="Descreva alguma observação que achar necessária" class="form-control input-md" type="text" maxlength="100" value="<?= $this->view->dadosNecessidade['obs_sobre_item'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="dsc_item_neces">Descrição do Item</label>
                <div class="col-lg-9">
                  <input id="dsc_item_neces" name="dsc_item_neces" placeholder="Descreva alguma coisa que achar necessária" class="form-control input-md" type="text" maxlength="100" value="<?= $this->view->dadosNecessidade['dsc_item_neces'] ?>">
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="qtd_item_neces">Quantidade do Item<h11>*</h11></label>  
                <div class="col-lg-2">
                  <input id="qtd_item_neces" name="qtd_item_neces" placeholder="Apenas números" class="form-control input-md" type="text" maxlength="15" onkeypress="return event.charCode >= 48 && event.charCode <= 57" value="<?= $this->view->dadosNecessidade['qtd_item_neces'] ?>">
                </div>
              </div>

              <div class="form-group">    
                <label class="col-md-2   control-label" for="cd_tip_unid_item">Tipo Item<h11>*</h11></label>
                <div class="col-lg-3">
                  <select id="cd_tip_unid_item" name="cd_tip_unid_item" class="form-control">
                    
                    <?php function selected8( $value, $selected ) {
                        return $value==$selected ? ' selected="selected"' : ''; } ?>

                    <option value="1"<?php echo selected8('1', $this->view->dadosNecessidade['cd_tip_unid_item']); ?>>Peça</option>
                    
                    <option value="2"<?php echo selected8('2', $this->view->dadosNecessidade['cd_tip_unid_item']); ?>>Unidade</option>

                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="vlr_neces">Valor (R$)</label>
                <div class="col-lg-2">
                  <input id="dinheiro" name="vlr_neces" value="<?= $this->view->dadosNecessidade['vlr_neces'] ?>"maxlength="17" disabled="" class="dinheiro form-control" placeholder="Somente números" style="display:inline-block" />
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label" for="Cadastrar"></label>
                <div class="col-md-8">
                  <a href="#" onclick="sendPost('/fNIncluirNeces', {cb_grupo_escolhido:'<?= $this->view->dadosNecessidade['cd_grp'] ?>', cb_subgrupo_escolhido:'<?= $this->view->dadosNecessidade['cd_sbgrp'] ?>', cb_familia_escolhida:'<?= $this->view->dadosNecessidade['cd_fml'] ?>', cd_tip_evt_neces:'<?= $this->view->dadosNecessidade['cd_tip_evt_neces'] ?>'});" class="btn btn-success">Retorna</a>

                  <button class="btn btn-primary" type="button" id="btnIncluir">Cadastrar</button>

                  <a class="btn" id="btnOculto"></a>    
                </div>              
              </div>

              <!-- Campos para tratamento de retorno -->
              <input id="cd_tip_evt_neces" name="cd_tip_evt_neces" class="form-control input-md" disabled="" type="text" maxlength="2"  value="" hidden>
              <input type="hidden" name="cd_tip_evt_neces" value="<?= $this->view->dadosNecessidade['cd_tip_evt_neces'] ?>"> 

              <input id="cb_grupo_escolhido" name="cb_grupo_escolhido" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->dadosNecessidade['cd_grp'] ?>" hidden>
              <input type="hidden" name="cb_grupo_escolhido" value="<?= $this->view->dadosNecessidade['cd_grp'] ?>"> 

              <input id="cb_subgrupo_escolhido" name="cb_subgrupo_escolhido" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->dadosNecessidade['cd_sbgrp'] ?>" hidden>
              <input type="hidden" name="cb_subgrupo_escolhido" value="<?= $this->view->dadosNecessidade['cd_sbgrp'] ?>"> 
              <input id="cb_familia_escolhida" name="cb_familia_escolhida" class="form-control input-md" disabled="" type="text" maxlength="2"  value="<?= $this->view->dadosNecessidade['cd_fml'] ?>" hidden>
              <input type="hidden" name="cb_familia_escolhida" value="<?= $this->view->dadosNecessidade['cd_fml'] ?>"> 
              <!-- Término Campos para tratamento de retorno -->

            </div>
          </div>
        </form>
        </fieldset>
      </div>
    </section>

    <!-- Para formatar campos de entrada no formulário- não pode ficar em "layout.pthml" pois não executava -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    
    <script>
      // Para simular o clique do botão e abrir as opções de Item e Subitem
      <?php if ($this->view->erroValidacao >= 0 ) { ?>
        $(function() {
            $('#btnOculto').on("click", function () {
              $('#btnOculto').hide();
          });
          // Chama a função de clique através do trigger
          $("#btnOculto").trigger('click');
        })
      <?php } ?>

      $('#btnOculto').click(function(e){
          $("#cb_item_escolhido").removeAttr("disabled");
          $("#cb_subitem_escolhido").removeAttr("disabled");
          $('#cb_item_escolhido').empty().append('<option>Escolha Item</option>>');
          $('#cb_subitem_escolhido').empty().append('<option>Escolha Subitem</option>');

          var tipo_evt = 1;

          // Carrega Itens         
          $.getJSON('ConsultaCbDependente.php?opcao=itemEvtNeces&valor='+tipo_evt, 
            function (dados){
             if (dados.length > 0){    

                var option = '<option>Escolha Item</option>';

                $.each(dados, function(i, obj){
                    //option += '<option value="'+obj.cod_item+'">'+obj.nome_item+'</option>';
                    option += '<option value="'+obj.cod_item+';'+obj.nome_item+'">'+obj.nome_item+'</option>';
                })
             } else {
                Reset();
             }
             $('#cb_item_escolhido').html(option).show();
          })
      })

      // Carrega Subitens
      $('#cb_item_escolhido').change(function(e){
        var item = $('#cb_item_escolhido').val().split(';');

        item = item[0];

        // Para Habilitar valor somente se item = 6
        if (item == 7) {
          $("#dinheiro").removeAttr("disabled");
          $("#cd_tip_unid_item").val(2);
          $("#cd_tip_unid_item").attr("disabled", true);
        } else {
          $("#dinheiro").val('');
          $("#dinheiro").attr("disabled", "disabled");
        }

        // Para definir Almoxarifado quando item 1 a 4
        if (item >= 1 && item <= 4) {
          $("#cd_setor_resp").val(1);
          $("#cd_setor_resp").attr("disabled", true);

          $("#cd_tip_unid_item").val(2);
          $("#cd_tip_unid_item").attr("disabled", false);
        
        } else if (item == 5) {
          $("#cd_setor_resp").val(4);
          $("#cd_setor_resp").attr("disabled", true);
        
        } else if (item == 6) {
          $("#cd_setor_resp").val(7);
          $("#cd_setor_resp").attr("disabled", true);

          $("#cd_tip_unid_item").val(2);
          $("#cd_tip_unid_item").attr("disabled", true);
        
        } else if (item == 7) {
          $("#cd_setor_resp").val(3);
          $("#cd_setor_resp").attr("disabled", true);
        }

        $.getJSON('ConsultaCbDependente.php?opcao=subitem&valor='+item, 
        function (dados){ 
           if (dados.length > 0){    

              var option = '<option>Escolha Subitem</option>';

              $.each(dados, function(i, obj){
                  //option += '<option value="'+obj.cod_subitem+'">'+obj.nome_subitem+'</option>';
                  option += '<option value="'+obj.cod_subitem+';'+obj.nome_subitem+'">'+obj.nome_subitem+'</option>';
              })
              
           } else {
             Reset(); 
           }

           $('#cb_subitem_escolhido').html(option).show(); 
          })
      })
      
      // Resetar Selects //
      function Reset(){
        $('#cb_item_escolhido').empty().append('<option>Escolha Item</option>>');
        $('#cb_subitem_escolhido').empty().append('<option>Escolha Subitem</option>');

        <?php if ($this->view->erroValidacao >= 0 ) { ?>
          $(function() {
              $('#btnOculto').on("click", function () {
                $('#btnOculto').hide();
            });
            // Chama a função de clique através do trigger
            $("#btnOculto").trigger('click');
          })
        <?php } ?>
      }
    </script>  

    <script>
      // Script pego em "http://blog.conradosaud.com.br/artigo/26" para formatação de valores - link está em "layout.phtml" //
      $('.dinheiro').mask('#.##0,00', {reverse: true});
    </script>  

    <!-- Para mostrar Alerta de Confirma ou Não -->
    <script src="alertaConfirmaIncluiNecesProxVisita.js"></script>

    <!-- Para Possibilitar $_POST -->
    <script src="sendPost.js"></script>

  </body>
</html>