<!--  Nome Programador: Paulo Tarrago Jaques
      Data de criação: 11/07/2019                       
      Objetivo:  Definições de funcionalidades externas necessárias ao sistema
-->

<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">

		<title>Sistema de Gestão Auta de Souza</title>	

		<!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->

	    <!-- JQuery 
	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

		!-- Necessário para rodar Javascript com Bootstrap 
		<script src="http://code.jquery.com/jquery-3.4.1.min.js"
		  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>-->

		<!-- Em 21/09/2019, alterei para este abaixo e retirei os de cima -->
		<script src="jquery.min.js"></script>

		<!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<!--<link rel="/stylesheet" href="/bootstrap/dist/css/bootstrap.min.css">-->

	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	    <!-- Font Awesome -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

		<!-- Script para utilizar o SWEETALERT de mensagens de confirmação (ao invés do alert html -->
	   	<link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet"/>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
	
	    <!-- Estilos aplicados no sistema -->
	    <link rel="stylesheet" href="/css/style.css"/>
	    <link rel="stylesheet" href="/css/normalize.css"/>

	</head>
	
	<body>
		<?= $this->content() ?>
	</body>
</html>